apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: default
  source:
    path: platforms/hyperledger-fabric/charts/peernode
    repoURL: https://github.com/Karthikey22/bevel.git
    targetRevision: HEAD
    helm:
      releaseName: sample-app
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
