apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: manufacturer-operations-console
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: manufacturer-operations-console
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/operations_console
  values:
    metadata:
      namespace: manufacturer-net
      images:
        couchdb: couchdb:3.1.1
        console: "ghcr.io/hyperledger-labs/fabric-console:latest"
        configtxlator: hyperledger/fabric-tools:1.4.8
    storage:
      couchdb:
        storageclassname: manufacturersc
        storagesize: 512Mi
    service:
      name: manufacturerconsole
      default_consortium: SupplyChainConsortium
      serviceaccountname: default
      imagesecretname: regcred
      servicetype: ClusterIP
      ports:
        console:
          clusteripport: 3000
        couchdb:
          clusteripport: 5984
    proxy:    
      provider: "none"
      external_url_suffix: manufacturer-net:7054
