apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manufacturer-peer0
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Karthikey22/bevel.git
    path: platforms/hyperledger-fabric/charts/peernode
    targetRevision: HEAD
    helm:
      releaseName: manufacturer-peer0
      values: |-
          metadata:
            namespace: manufacturer-net
            images:
              couchdb: hyperledger/fabric-couchdb:0.4.18
              peer: hyperledger/fabric-peer:1.4.8
              alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
              
          peer:
            name: peer0
            gossippeeraddress: peer0.manufacturer-net:7051
            gossipexternalendpoint: peer0.manufacturer-net:7051
            localmspid: manufacturerMSP
            loglevel: info
            tlsstatus: true
            builder: hyperledger/fabric-ccenv:1.4.8
            couchdb:
              username: manufacturer-user

          storage:
            peer:
              storageclassname: manufacturersc
              storagesize: 512Mi
            couchdb:
              storageclassname: manufacturersc
              storagesize: 1Gi

          vault:
            role: vault-role
            address: http://52.229.229.54:8200
            authpath: localmanufacturer-net-auth
            secretprefix: secretsv2/data/crypto/peerOrganizations/manufacturer-net/peers/peer0.manufacturer-net
            secretambassador: secretsv2/data/crypto/peerOrganizations/manufacturer-net/ambassador
            serviceaccountname: vault-auth
            imagesecretname: regcred
            secretcouchdbpass: secretsv2/data/credentials/manufacturer-net/couchdb/manufacturer?user

          service:
            servicetype: ClusterIP
            ports:
              grpc:
                clusteripport: 7051
              events:
                clusteripport: 7053
              couchdb:
                clusteripport: 5984
                      
          proxy:
            provider: "none"
            external_url_suffix: upgrade.upgrade.com

          config:
            pod:
              resources:
                limits:
                  memory: 512M
                  cpu: 1
                requests:
                  memory: 512M
                  cpu: 0.5
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      # Do not enable pruning yet!
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true
