apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.244.7.50:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaILBJjnrw9MMwgDgzumGohKRyHkXKeQcYsfGjrNuIkc+7EqxeCqleCqZeCngKWggBEAEaBgiJ
      5PmhBiIKc3lzY2hhbm5lbCpANTE1NTczOGFjNjZkZWRlYWI0MjRlMWE5NGUzYmQxNWQyYmMxNGI4
      MWM2MTc0Y2Y3Y2I2ZTEyYTQyNjAwNjlhNxIaEhgypglCPwvG/gfyyQXjqmvd1B9lu3gDb7kSqV0K
      pl0So10SkysKB09yZGVyZXIShysSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekND
      QWFhZ0F3SUJBZ0lVUUgyek5GMS9JZEpieWtzL1Q4ZWhuaGEzT3hFd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TkRFNE1UQXhPVFUxV2hjTk1qWXdNakExTVRBeE9UVTFX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJQOGgr
      aG9mK1dXTCthbHQyUzd4ZExFeGZzMHNaUUZuL1RvQ3VBKzI0K3R6Mk1lT2tMTkwKaU14WjBUQWtS
      MXRLTnF0ckFuMzNVUkUxOFhZK3J1NHRrd3VqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU2V6V2VXeVpBYVV5VzRzWHE1OGE3NW9K
      WXdsVEFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlBNW5Ic2J2bEdZcG0rTzBZSzNGVTN6RkRMb0V3
      M25tSWNsNG5WalNkVGcKaHdJZ1k4dWhlU1NkdUFYTzN2b3ZxdlNTdjd5WEhoNTlOSnBFZEdvVm5h
      Sjcrdms9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVRjZ2ZTRkK1pFTkpRcFkrbHdYZDdBaDdHQmJFd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TkRFNE1UQXlOVEF3V2hjTk1q
      UXdOREUzTVRBek1EQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFelBnQ2ZKMXJGRVNaa1B3akRUOXc4SzNZQVRI
      Tm1iMncKMDJPc2dmZElwV0kzcjhtSHU0WU13TXR1cnRidndUNTJXU25lU1RsSFMvd0lXeERzRVZH
      aDJLT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJUVlRtcGJvbTMvCjVDWnBoWmtRWnlOcnl4VWJTREFmQmdOVkhTTUVHREFXZ0JT
      ZXpXZVd5WkFhVXlXNHNYcTU4YTc1b0pZd2xUQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qbG1ZMlptWkdSakxXZzJhM0UzTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnWDVuZmRaTEdyTll6d0NCOVBlUkFVcGNSQXQycGdoZlJlNW9DZWRhQngzZ0NJQmZT
      Lyt2Mjc3cFE0U1hSCjVtOHhOV2VsMTZoa3JiTW1oTjc4Z2lXYmJBRGwKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUIvekNDQWFhZ0F3SUJBZ0lVUUgyek5GMS9JZEpieWtzL1Q4ZWhuaGEzT3hFd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TkRFNE1UQXhPVFUxV2hjTk1qWXdNakEx
      TVRBeE9UVTFXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJQOGgraG9mK1dXTCthbHQyUzd4ZExFeGZzMHNaUUZuL1RvQ3VBKzI0K3R6Mk1lT2tMTkwK
      aU14WjBUQWtSMXRLTnF0ckFuMzNVUkUxOFhZK3J1NHRrd3VqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU2V6V2VXeVpBYVV5VzRz
      WHE1OGE3NW9KWXdsVEFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlBNW5Ic2J2bEdZcG0rTzBZSzNG
      VTN6RkRMb0V3M25tSWNsNG5WalNkVGcKaHdJZ1k4dWhlU1NkdUFYTzN2b3ZxdlNTdjd5WEhoNTlO
      SnBFZEdvVm5hSjcrdms9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0
      aW9ucxIIGgZBZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGooS
      Cg1Db25zZW5zdXNUeXBlEvgREu0RCghldGNkcmFmdBLgEQrJEQoYb3JkZXJlcjEuc3VwcGx5Y2hh
      aW4tbmV0EIo3GtMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQXF1Z0F3SUJB
      Z0lVTUFydDFiNmJ6TTBMb3R4R0dBMGtCNy9XNThjd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJp
      MXVaWFF3CkhoY05Nak13TkRFNE1UQXlOVEF3V2hjTk1qUXdOREUzTVRBek1EQXdXakJ4TVFzd0NR
      WURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0Rn
      WURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4
      aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhr
      ak9QUU1CQndOQ0FBUkg0Y0ZSeUNRN0doUVozK1Yvd3VpcllPQzkKUGpwRERGc080dkVITHpFQlVz
      OUdyMzFxa0RYUmg1OUFpYXlLS1VmdGZPRnAydm1mVjRpZGZhUmlLRWpubzRJQgpNakNDQVM0d0Rn
      WURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJR
      Y0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUmpYYWR5SFZ6SnRXUHNlNlFaY3FL
      S3BnOXMKTHpBZkJnTlZIU01FR0RBV2dCU2V6V2VXeVpBYVV5VzRzWHE1OGE3NW9KWXdsVEJCQmdO
      VkhSRUVPakE0Z2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0hHOXlaR1Z5WlhJ
      eExuVndaM0poWkdVdWRYQm5jbUZrClpTNWpiMjB3YkFZSUtnTUVCUVlIQ0FFRVlIc2lZWFIwY25N
      aU9uc2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSWkKTENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lK
      dmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFFpTENKbwpaaTVVZVhCbElqb2liM0prWlhK
      bGNpSjlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUE0bHpUSVIzUDJEYXo0CkJPbE96czIrVGh3
      QkRjaEMwdEhWL014TTIzZytvQUlnUGhyNUVxM1JXTW1qay9aVFRiVlI4K1NJSVpXODZnNjkKa3A3
      TWc0THlKajQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KItMILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSURCRENDQXF1Z0F3SUJBZ0lVTUFydDFiNmJ6TTBMb3R4R0dBMGtCNy9XNThj
      d0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZ
      RFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TkRFNE1UQXlOVEF3V2hj
      Tk1qUXdOREUzTVRBek1EQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRF
      dU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFR
      TEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1
      ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUkg0Y0ZSeUNRN0doUVozK1Yv
      d3VpcllPQzkKUGpwRERGc080dkVITHpFQlVzOUdyMzFxa0RYUmg1OUFpYXlLS1VmdGZPRnAydm1m
      VjRpZGZhUmlLRWpubzRJQgpNakNDQVM0d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFX
      TUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVk
      RGdRV0JCUmpYYWR5SFZ6SnRXUHNlNlFaY3FLS3BnOXMKTHpBZkJnTlZIU01FR0RBV2dCU2V6V2VX
      eVpBYVV5VzRzWHE1OGE3NW9KWXdsVEJCQmdOVkhSRUVPakE0Z2hodgpjbVJsY21WeU1TNXpkWEJ3
      YkhsamFHRnBiaTF1WlhTQ0hHOXlaR1Z5WlhJeExuVndaM0poWkdVdWRYQm5jbUZrClpTNWpiMjB3
      YkFZSUtnTUVCUVlIQ0FFRVlIc2lZWFIwY25NaU9uc2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSWkK
      TENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lKdmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVa
      WFFpTENKbwpaaTVVZVhCbElqb2liM0prWlhKbGNpSjlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVB
      aUE0bHpUSVIzUDJEYXo0CkJPbE96czIrVGh3QkRjaEMwdEhWL014TTIzZytvQUlnUGhyNUVxM1JX
      TW1qay9aVFRiVlI4K1NJSVpXODZnNjkKa3A3TWc0THlKajQ9Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAoaBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICA
      MRiAgEAaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5z
      IiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoH
      V3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zKgZBZG1p
      bnMSxy8KC0NvbnNvcnRpdW1zErcvEuwuChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0S0i4SuxcKD21h
      bnVmYWN0dXJlck1TUBKnFxqvFQoDTVNQEqcVEpwVEpkVCg9tYW51ZmFjdHVyZXJNU1AShgYtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0RUQ0NBYktnQXdJQkFnSVVMYm5RRFNmamZrRHFS
      SXB5Q01DYklaaXNCQ293Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5C
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5Z
      VzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdI
      aGNOTWpNd05ERTRNVEF5TVRFMVdoY05Nall3TWpBMU1UQXlNVEUxV2pCa01Rc3dDUVlEVlFRRwpF
      d0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJn
      TlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNt
      VnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJMZytuVW01RUdaejAw
      eHp0OFlGZTRySlh1a2l6RE5LU3NGMApYNDk2WkVqRDJwejZ3cFlzMitQcjFtMXNHV1FNUUlTR05G
      VUVVQ1RCRUMvdTJDb2FKMU9qUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFR
      SC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0ZZMXlYVjFQVU5UUHcKclp3d1ZLUnorRlpxY1RBS0Jn
      Z3Foa2pPUFFRREFnTkpBREJHQWlFQXJhSFBPeU5udUFnbFlZclNXSlIvcFh4KwpDU3ZMcTVDU0FZ
      ZHBsOUJoQmF3Q0lRQ2lNTy8rN3J6V1dSdnQ0YjJiYjlIcUVEc3lidWl4aUhHUzJmWlBaUys2Cm53
      PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJREVUQ0NBcmVnQXdJQkFnSVVINVcrNjNoWDNFaURJU0duN2ZkVlVENTdYRkV3Q2dZSUtv
      Wkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJn
      TlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpNd05ERTRNVEF5TnpBd1do
      Y05NalF3TkRFM01UQXpNakF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFjVEVU
      UTNMak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJeEl6
      QU1CZ05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZRFZR
      UUREQlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29a
      SQp6ajBEQVFjRFFnQUVZTGFRV21kU0JSR0pmVVVMUWhSbzFsTUx3b2x0dmE1bVhJZTU0S0hLcTNH
      eWpOL3h1bjdCClNMeXR2MGk5ZDM2UTVjZldNMWNUUU9kb0JLUFpBcEl2WmFPQ0FTSXdnZ0VlTUE0
      R0ExVWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNvN0lX
      ODh4Zzlub0FSWU03cFlCYjBWNCtUYXpBZgpCZ05WSFNNRUdEQVdnQlNGWTF5WFYxUFVOVFB3clp3
      d1ZLUnorRlpxY1RBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAzWm1Oa1kyWm1ObUprTFdS
      NllqYzJNSUdYQmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdKaFl5NXBibWwwSWpv
      aWRISjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dQpJam9pYldG
      dWRXWmhZM1IxY21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWJXRnVkV1po
      ClkzUjFjbVZ5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9QUVFE
      QWdOSUFEQkYKQWlFQXhQa1J1SnVsUUFCMkgzcGNBOVdyNjFBU0ZuMHhaZEpJYi9ZZ2NKclBDcW9D
      SUE2S0xPN1ZvUDZaQjEyZgowdTlVajNFS2U0UGVGNHU2eVBFemM4S0FsVVdWCi0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkqGBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDRFRDQ0FiS2dBd0lCQWdJVUxiblFEU2ZqZmtEcVJJcHlDTUNiSVppc0JDb3dDZ1lJ
      S29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQ
      TUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFh
      QmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nak13TkRFNE1UQXlNVEUx
      V2hjTk1qWXdNakExTVRBeU1URTFXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdH
      V25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04w
      ZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFH
      U000OUFnRUdDQ3FHU000OUF3RUhBMElBQkxnK25VbTVFR1p6MDB4enQ4WUZlNHJKWHVraXpETktT
      c0YwClg0OTZaRWpEMnB6NndwWXMyK1ByMW0xc0dXUU1RSVNHTkZVRVVDVEJFQy91MkNvYUoxT2pR
      akJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWRE
      Z1FXQkJTRlkxeVhWMVBVTlRQdwpyWnd3VktSeitGWnFjVEFLQmdncWhrak9QUVFEQWdOSkFEQkdB
      aUVBcmFIUE95Tm51QWdsWVlyU1dKUi9wWHgrCkNTdkxxNUNTQVlkcGw5QmhCYXdDSVFDaU1PLys3
      cnpXV1J2dDRiMmJiOUhxRURzeWJ1aXhpSEdTMmZaUFpTKzYKbnc9PQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tChoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVm
      YWN0dXJlck1TUBABGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIR
      Cg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMS
      EQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoT
      EhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zKgZBZG1pbnMSthYKCmNhcnJpZXJNU1ASpxYawxQK
      A01TUBK7FBKwFBKtFAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlCK0RDQ0FaNmdBd0lCQWdJVUxicHJFaTJTeU1iQmpyUytCZFFZSjl0M21lTXdDZ1lJS29aSXpq
      MEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allT
      NWpZWEp5YVdWeUxXNWxkREFlRncweQpNekEwTVRneE1ESXlNekphRncweU5qQXlNRFV4TURJeU16
      SmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJB
      Y01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVky
      RnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVRWdmQ2M2VJ
      bkk5WXN0L3I5dGovREZzNmdCczJQSFcyR0dvMERDQWlDajFnMU1rT1lnM0ZyUkY2SU1IeXJhCnFl
      TThlVHNxQlB0dnJVWlQwQm44ZGhyRm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFV
      ZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVVmpHWE5tUjRySDRXVGVaV1hvT1RUaXltTjdZ
      d0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBS1VIMVhJZDJZb0M4QXh6aXVlSHg0WEUzc2xWOFZ6
      M1dnZWl0dlNrZjR3bkFpQWR0K3NtCjlGL1lEVWFvL2R6YTBac1RTVkczZ3gzalY5bkE5SUoxVHFC
      VnRnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoitggtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQzdqQ0NBcFNnQXdJQkFnSVVCeHl1cTJqeW1XaVFsblNxOHc5bEMxWEt6ZkV3Q2dZ
      SUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFR
      RERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTXpBME1UZ3hNREk0TURCYUZ3MHlOREEwTVRj
      eE1ETXpNREJhTUhneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0
      eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RCV0ZrYlds
      dU1BNEdBMVVFQ3hNSFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kx
      dVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBU3YrZ2w5RXVpcmswZVN6d2Ro
      dW93VApWSU9RVlhQcElZYkM0QWZwcFlvbVNHT1BCNlBRT2FVT1d0cnVtbkE0RFM2Vk9Nc3oxTEdw
      aklvejZQUkpqMUdkCm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VC
      L3dRQ01BQXdIUVlEVlIwT0JCWUUKRkwvaFhVaXpHd2d2SFdReHhad0NONUxjbDZ3cU1COEdBMVVk
      SXdRWU1CYUFGRll4bHpaa2VLeCtGazNtVmw2RAprMDRzcGplMk1DUUdBMVVkRVFRZE1CdUNHV05o
      TFhSdmIyeHpMVGRpTlRZNU9EWTROVFl0YUhFMGNUUXdnWTBHCkNDb0RCQVVHQndnQkJJR0FleUpo
      ZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lKMGNuVmxJaXdp
      YUdZdVFXWm1hV3hwWVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxF
      SWpvaVFXUnRhVzVBWTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdD
      Z1lJCktvWkl6ajBFQXdJRFNBQXdSUUloQUpvVTUyMUZ0UkdOc3dLbGtkTi92VW1hRGxySUlTM0Js
      Zy9EbG5tUkNmRjUKQWlBbWN2bHJQSEZCVy9NaUtoMTdibXFyMHVxc0xWZlk2bnR6di9IbGIycXE5
      QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVUxicHJFaTJTeU1iQmpyUytC
      ZFFZSjl0M21lTXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZC
      QWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlh
      V1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNekEwTVRneE1ESXlN
      ekphRncweU5qQXlNRFV4TURJeU16SmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlE
      QVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNq
      RVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhr
      ak9QUU1CQndOQwpBQVRWdmQ2M2VJbkk5WXN0L3I5dGovREZzNmdCczJQSFcyR0dvMERDQWlDajFn
      MU1rT1lnM0ZyUkY2SU1IeXJhCnFlTThlVHNxQlB0dnJVWlQwQm44ZGhyRm8wSXdRREFQQmdOVkhS
      TUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVVmpHWE5t
      UjRySDRXVGVaV1hvT1RUaXltTjdZd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBS1VIMVhJZDJZ
      b0M4QXh6aXVlSHg0WEUzc2xWOFZ6M1dnZWl0dlNrZjR3bkFpQWR0K3NtCjlGL1lEVWFvL2R6YTBa
      c1RTVkczZ3gzalY5bkE5SUoxVHFCVnRnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFk
      bWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFk
      bWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5z
      IjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiNAoG
      QWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMqBkFkbWlu
      cxpAChVDaGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRl
      cmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIA
      GhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaLQoZQmxv
      Y2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxpOChBPcmRlcmVyQWRkcmVz
      c2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIv
      QWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8zEgAaBkFkbWlucxomChBIYXNoaW5n
      QWxnb3JpdGhtEhISCAoGU0hBMjU2GgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxAC
      GgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIX
      Eg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
