apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://51.103.210.41:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIK3NVxqBj3Z3zlTQkR5mNAcwvc+u1pdqlIWcehuVoS6BEp5eCpteCpheCngKWggBEAEaBgjp
      /cacBiIKc3lzY2hhbm5lbCpANzljNzQzMjJkODUyMjVkN2NmZDc5MzM5ZGMxMzIzMTUwYTQyNGRm
      ZmQ4ZmQ3NTZhYThkNjUxOGYzNzg0OTkxMRIaEhiQ92CkgCZILgdRL+2hh9BiVhxM05WoHKESm10K
      mF0SlV0SkysKB09yZGVyZXIShysSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVTlU4aDdNV0RHWEZ4L1JmNmtiMWI2OHBvallzd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBNE1UQXlOVFV4V2hjTk1qVXdPVEkzTVRBeU5UVXhX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJDaGoy
      KzhpVlJISzd5QXhOVUlaalpYWnBCUmdQUDVSV1dFbUNOTTczMnlOVUFnc0tWUFYKV3ZZYWlGRGN5
      dHdWRHdtTDFBaVFsdFBIK3pLMVcxWEVCUjJqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUlR4T0NZVlYyTk45Snk1RFJsZG92enlo
      elc2ekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQW03OFhQN21qMGlRbTVYU0J2a2lqblIweWxE
      SHA4bk5Vd2xkeUpMdTMKdHdZQ0lDZmdTNEl5T2JLV1RLWUMwRTNFUlRnMFRvbzg1WWpqT2lnVWFP
      R0tuNVdOCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVVU9UZEI2dStYNlN5ZHk0akZsVXhzeEpMYUVVd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBNE1UQXpNakF3V2hjTk1q
      TXhNakE0TVRBek56QXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFT0NJZHplYXRDV2dabnFsVlZZV01VeWNreXVq
      OVpQUUMKUjluYU9kRFJZV2xFVFRudWU0dVF6aXdWWklkS3k4YXVKVnBGSjhyT0VmbzVVbitNMkNY
      Si82T0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJTMFRPTmpkN0xwCjlWOERtcVRBeElyZ3ZNUzVTekFmQmdOVkhTTUVHREFXZ0JS
      VHhPQ1lWVjJOTjlKeTVEUmxkb3Z6eWh6VzZ6QWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      M09UZG1OVGMxTnpkbUxUbGtPSFptTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnY3psL0tqNThaKzNtZDlOdGJZMzd4UmpySm9vTzNlalpLcksxcU5VSE9UNENJRlNW
      QW1LNlVIVUZzUDd3CmVSZ0dqT3JVbGlLOVNHSXdiT0tjUkhXZjk1ZW4KLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVTlU4aDdNV0RHWEZ4L1JmNmtiMWI2OHBvallzd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBNE1UQXlOVFV4V2hjTk1qVXdPVEkz
      TVRBeU5UVXhXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJDaGoyKzhpVlJISzd5QXhOVUlaalpYWnBCUmdQUDVSV1dFbUNOTTczMnlOVUFnc0tWUFYK
      V3ZZYWlGRGN5dHdWRHdtTDFBaVFsdFBIK3pLMVcxWEVCUjJqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUlR4T0NZVlYyTk45Snk1
      RFJsZG92enloelc2ekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQW03OFhQN21qMGlRbTVYU0J2
      a2lqblIweWxESHA4bk5Vd2xkeUpMdTMKdHdZQ0lDZmdTNEl5T2JLV1RLWUMwRTNFUlRnMFRvbzg1
      WWpqT2lnVWFPR0tuNVdOCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91
      dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJgoMQ2Fw
      YWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGooSCg1Db25zZW5zdXNUeXBlEvgREu0R
      CghldGNkcmFmdBLgEQrJEQoYb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3GtMILS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQXF1Z0F3SUJBZ0lVYjFqcUd6RXZFSUI5RGhhaTNJ
      S2ZjU1RZYlF3d0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJB
      Z01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNt
      VnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBNE1U
      QXpNakF3V2hjTk1qTXhNakE0TVRBek56QXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0Ex
      VUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJB
      dwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3Ykhs
      amFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVElyTE5wTkJv
      V2FJcCtrU2NzSkJxd041VTEKYkJmLzFnMEdLSGRpeWx4b1VrdTZGbFRtNU84Q09QeHErN0poZlVL
      RDYvMjBQaFFpNkxnWHB4VEVEL3E3bzRJQgpNakNDQVM0d0RnWURWUjBQQVFIL0JBUURBZ09vTUIw
      R0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCVHJuMkdFZXh6Z2psQ0ZYSWtFR2JQdmVMRmUKVFRBZkJnTlZIU01FR0RB
      V2dCUlR4T0NZVlYyTk45Snk1RFJsZG92enloelc2ekJCQmdOVkhSRUVPakE0Z2hodgpjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0hHOXlaR1Z5WlhJeExuVndaM0poWkdVdWRYQm5jbUZr
      ClpTNWpiMjB3YkFZSUtnTUVCUVlIQ0FFRVlIc2lZWFIwY25NaU9uc2lhR1l1UVdabWFXeHBZWFJw
      YjI0aU9pSWkKTENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lKdmNtUmxjbVZ5TVM1emRYQndiSGxq
      YUdGcGJpMXVaWFFpTENKbwpaaTVVZVhCbElqb2liM0prWlhKbGNpSjlmVEFLQmdncWhrak9QUVFE
      QWdOSEFEQkVBaUFqei9tNFh1dlF4MlIyCjJEa3BVSnBuaitFMVVhTDdPTGIwaWxQQlplY3dOZ0ln
      ZjNySndudkdtNk1NdVc4cnBsSTFUYjNDd1JrK1Y1eWEKanR1bzlDMHpDcUU9Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KItMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQXF1
      Z0F3SUJBZ0lVYjFqcUd6RXZFSUI5RGhhaTNJS2ZjU1RZYlF3d0NnWUlLb1pJemowRUF3SXcKWGpF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxq
      YUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBNE1UQXpNakF3V2hjTk1qTXhNakE0TVRBek56QXdXakJ4
      TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1
      TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lE
      VlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQ0FBVElyTE5wTkJvV2FJcCtrU2NzSkJxd041VTEKYkJmLzFnMEdLSGRp
      eWx4b1VrdTZGbFRtNU84Q09QeHErN0poZlVLRDYvMjBQaFFpNkxnWHB4VEVEL3E3bzRJQgpNakND
      QVM0d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JC
      Z0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVHJuMkdFZXh6Z2psQ0ZY
      SWtFR2JQdmVMRmUKVFRBZkJnTlZIU01FR0RBV2dCUlR4T0NZVlYyTk45Snk1RFJsZG92enloelc2
      ekJCQmdOVkhSRUVPakE0Z2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0hHOXla
      R1Z5WlhJeExuVndaM0poWkdVdWRYQm5jbUZrClpTNWpiMjB3YkFZSUtnTUVCUVlIQ0FFRVlIc2lZ
      WFIwY25NaU9uc2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSWkKTENKb1ppNUZibkp2Ykd4dFpXNTBT
      VVFpT2lKdmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFFpTENKbwpaaTVVZVhCbElqb2li
      M0prWlhKbGNpSjlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUFqei9tNFh1dlF4MlIyCjJEa3BV
      SnBuaitFMVVhTDdPTGIwaWxQQlplY3dOZ0lnZjNySndudkdtNk1NdVc4cnBsSTFUYjNDd1JrK1Y1
      eWEKanR1bzlDMHpDcUU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAF
      KICAgAoaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0
      ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIa
      BkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1p
      bnMSuS8KC0NvbnNvcnRpdW1zEqkvEt4uChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SxC4SsRcKD21h
      bnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVGaW9sZnZhRjVOZEtR
      UFNqQmtOd29TeW00MlV3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5C
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5Z
      VzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdI
      aGNOTWpJeE1qQTRNVEF5TmpVNFdoY05NalV3T1RJM01UQXlOalU0V2pCa01Rc3dDUVlEVlFRRwpF
      d0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJn
      TlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNt
      VnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJLSUtvVWtlTW9OQXg5
      TXZoUm5oVU0yVzMxdjlreEJ6M3RsQQpZUGdPUUJQSm01YlhYUVZsdXdVM0pxanFNRFlmTEI1S0tB
      elRPTGhNZDVQNVA5SENIYk9qUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFR
      SC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVENWMnY4UElQTVZjbkMKUDAybkQ1R3M2M2loTkRBS0Jn
      Z3Foa2pPUFFRREFnTklBREJGQWlFQW5lRFlFdk13eDRWYUxlQWo2YkZIOXV5cgpjU3VWclpRVXNh
      MHhxWFFTNy9FQ0lDL2tzcVM2ZG1QcXBrRGJlenFCaENyd2YrUXdDaTFBVDBwVjNkK0tWeDZOCi0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SURFRENDQXJlZ0F3SUJBZ0lVYk9PWGt4YUVTa2R3NlZKMkVDMkZnTndNNnBZd0NnWUlLb1pJemow
      RUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFV
      RUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFN
      TUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNakE0TVRBek16QXdXaGNOTWpN
      eE1qQTRNVEF6T0RBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEzTGpN
      NEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFNQmdO
      VkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFEREJa
      QlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkKemow
      REFRY0RRZ0FFM091WGJKd0hHSHltNlh0WnZpdkJpT1U2UFNHT2FVMldxQ2JWZkdrS3Vla0JwRjlL
      WE90TwpOZEpXMjl0cjdXYXpEeWVRQld3RjNJUlcrelN6dDhXVk9hT0NBU0l3Z2dFZU1BNEdBMVVk
      RHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJTZUh6RFhqSjRn
      SmYyRWNReUk3SnRQRUlYbWp6QWYKQmdOVkhTTUVHREFXZ0JUQ1YydjhQSVBNVmNuQ1AwMm5ENUdz
      NjNpaE5EQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwM05HSTFPRFpqT1dRNExUazVhSE5z
      TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lkSEox
      WlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVkV1po
      WTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZM1Ix
      Y21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTkhB
      REJFCkFpQndsM1pxYkpzeGpmS0I3eGM2S2FsTWhyM3Bqb1Jtdi8ySGFwYS9TRVFHVmdJZ0l0Mi8z
      WXUyM3pwN2J2VncKbDJScmxOcjkybGJZSUNCTzRUNlBBd3dnRitFPQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQ0REQ0NBYktnQXdJQkFnSVVGaW9sZnZhRjVOZEtRUFNqQmtOd29TeW00MlV3Q2dZSUtvWkl6
      ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdB
      MVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZC
      QU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1qQTRNVEF5TmpVNFdoY05N
      alV3T1RJM01UQXlOalU0V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlh
      V05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxj
      akVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlB
      Z0VHQ0NxR1NNNDlBd0VIQTBJQUJLSUtvVWtlTW9OQXg5TXZoUm5oVU0yVzMxdjlreEJ6M3RsQQpZ
      UGdPUUJQSm01YlhYUVZsdXdVM0pxanFNRFlmTEI1S0tBelRPTGhNZDVQNVA5SENIYk9qUWpCQU1B
      OEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JC
      VENWMnY4UElQTVZjbkMKUDAybkQ1R3M2M2loTkRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQW5l
      RFlFdk13eDRWYUxlQWo2YkZIOXV5cgpjU3VWclpRVXNhMHhxWFFTNy9FQ0lDL2tzcVM2ZG1QcXBr
      RGJlenFCaENyd2YrUXdDaTFBVDBwVjNkK0tWeDZOCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      GgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1cmVyTVNQ
      EAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0
      dXJlck1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFj
      dHVyZXJNU1AaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZh
      Y3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxKyFgoKY2Fycmllck1TUBKjFhq/FAoDTVNQErcUEqwU
      EqkUCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2
      Z0F3SUJBZ0lVRGxHU0R2blZ6SlFydG9uMTkrVnFNSWpTbE9Zd0NnWUlLb1pJemowRUF3SXcKV2pF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5
      TFc1bGREQWVGdzB5Ck1qRXlNRGd4TURJNE1UQmFGdzB5TlRBNU1qY3hNREk0TVRCYU1Gb3hDekFK
      QmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2
      YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1
      WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUmtWcTNUVUxUVnhwY1QwUUF5
      UlVsS29LekRXMGg1d3RUQ3B4dStaTFNGUHVkSmxlWHlocWZqVmtvMmxWSUgKNHpSVFYybUkrcnVY
      eXEvV1ZmWXN6Wi9qbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FF
      QXdJQnBqQWRCZ05WSFE0RUZnUVVwZ0J1cDhSOThXa2x0MHdWK1d6ZGNoSFNPR1l3Q2dZSUtvWkl6
      ajBFCkF3SURTQUF3UlFJaEFOOVBZSGpKRjJibFZpT2pFeEhsdmRRRDFCcXh2c094TXVwZGJNQUtv
      MG8rQWlBV1IrU1gKaUh0OGpEU0dTcXh6N0xpS09aK3Y2U3dQc3lrZmkyNzNHUlRWb2c9PQotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlD
      N1RDQ0FwT2dBd0lCQWdJVUFpY2hFdVM0bStucnNWY3pIWTF0cFpnaHcvNHdDZ1lJS29aSXpqMEVB
      d0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVC
      d3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZ
      WEp5YVdWeUxXNWxkREFlRncweQpNakV5TURneE1ETTBNREJhRncweU16RXlNRGd4TURNNU1EQmFN
      SGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWti
      MjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVD
      eE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRC
      Z2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRZG5Rbk1kT2s4dWNVbkY5NGFtbU5hCnZWS0JH
      eTd0Wk9vd01Oall2R2lmb0pFVHRPVlQxQ0lWSkNDQTRIVUpEU2RsdHA3cmdkaUN0blBpNXdGSmNG
      U04KbzRJQkZ6Q0NBUk13RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hR
      WURWUjBPQkJZRQpGQVdtenl3Sk1QNzl6ZWNXR0pSeWkweWpxaHN2TUI4R0ExVWRJd1FZTUJhQUZL
      WUFicWZFZmZGcEpiZE1GZmxzCjNYSVIwamhtTUNNR0ExVWRFUVFjTUJxQ0dHTmhMWFJ2YjJ4ekxU
      azVPVFJtWmpZNE9DMXdiblpyWXpDQmpRWUkKS2dNRUJRWUhDQUVFZ1lCN0ltRjBkSEp6SWpwN0lt
      RmlZV011YVc1cGRDSTZJblJ5ZFdVaUxDSmhaRzFwYmlJNgpJblJ5ZFdVaUxDSm9aaTVCWm1acGJH
      bGhkR2x2YmlJNkltTmhjbkpwWlhJaUxDSm9aaTVGYm5KdmJHeHRaVzUwClNVUWlPaUpCWkcxcGJr
      QmpZWEp5YVdWeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3EKaGtqT1BR
      UURBZ05JQURCRkFpRUF2cSt5R0xJUVZPRlBwMXZLQVhwY3AydGdXWTNuMEJJWDdDMVlOeGlQV3ZV
      QwpJSEVmVG9iMTFDRUx2WVc1TFBHWU1sWG0xNy9ZWGg5Q28xcUJqRmx0cDlGMgotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVEbEdTRHZuVnpKUXJ0b24xOStWcU1JalNsT1l3Q2dZ
      SUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFR
      RERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFeU1EZ3hNREk0TVRCYUZ3MHlOVEE1TWpj
      eE1ESTRNVEJhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpB
      TkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3
      T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFS
      a1ZxM1RVTFRWeHBjVDBRQXlSVWxLb0t6RFcwaDV3dFRDcHh1K1pMU0ZQdWRKbGVYeWhxZmpWa28y
      bFZJSAo0elJUVjJtSStydVh5cS9XVmZZc3paL2pvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgv
      TUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVXBnQnVwOFI5OFdrbHQwd1YrV3pk
      Y2hIU09HWXdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQU45UFlIakpGMmJsVmlPakV4SGx2ZFFE
      MUJxeHZzT3hNdXBkYk1BS28wbytBaUFXUitTWAppSHQ4akRTR1NxeHo3TGlLT1ordjZTd1BzeWtm
      aTI3M0dSVFZvZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiMwoHUmVhZGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigS
      HggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIc
      EggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggB
      EhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENy
      ZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0S
      EhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////
      DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5zdXBwbHljaGFpbi1u
      ZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZW
      MV80XzMSABoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1Jl
      YWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVy
      cxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
