apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://98.70.9.151:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIHk3HKrDAdUqeu3uhfMOx4Z1wGfcqxHONsQwZc8g+RKgEqJeCp9eCpxeCngKWggBEAEaBgid
      g5mjBiIKc3lzY2hhbm5lbCpANGRkZGY5MWRiNjEyZDYxZjYzNWFlYjAwNTUxNDg1ZjQwYzljYTUw
      Mjc5NjI2M2U1YjRlMjBlY2Y1MjhhZGIxZBIaEhj7gBfAfWngyTxOvHdDqZVzXy4KiPa/VX4Sn10K
      nF0SmV0SmSsKB09yZGVyZXISjSsS0hYKDnN1cHBseWNoYWluTVNQEr8WGssUCgNNU1ASwxQSuBQS
      tRQKDnN1cHBseWNoYWluTVNQEvUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVEND
      QWFhZ0F3SUJBZ0lVVTB1T2FBQmlPL3htMERKemRFNHM2N0JsZG5Vd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRFNE1UVXdPREUxV2hjTk1qWXdNekEzTVRVd09ERTFX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJNYm9w
      RGsvWXBVTUdqVkJHNXl1UU1FYVVVTW1VMUM3bUpNSHF0U1pab1ZFNExKUDZocysKYWZJaEhES1hP
      ZlN2SXRJeHNQaWpvS0NOZ2lOWS91Q3VkUk9qUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0N6KzgrUlhkYUdUWUhPUURnVmIxVFE3
      eDBvREFLCkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQTFMdjBkZ0N3VG5tU0lHTERXek9xOFVxakJO
      RDZFV0hKMDUvdWVrcDUKZjZZQ0lRRHFYYTd4Rjh2S0NkYWc2S01vdWVxbjRjMFZvcU9Na21KdDBS
      Y2tOa25pOUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKiCC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDNFRDQ0FvaWdBd0lCQWdJVWVaSWE2czg3TVgrdjhaTHJ2eFR4T1FraTFX
      b3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dR
      WURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd05URTRNVFV3T1RBd1do
      Y05NalF3TlRFM01UVXhOREF3V2pCc01Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05U
      RXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1RNHcKREFZRFZR
      UUxFd1ZoWkcxcGJqRWVNQndHQTFVRUF3d1ZRV1J0YVc1QWMzVndjR3g1WTJoaGFXNHRibVYwTUZr
      dwpFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWd0YUNieEQ1MWNSZUNOYnlaQVNDTTZO
      QldKRTFWVTFRCmpMYkhmRHVHbDVQbFFDdWp5UXV3YkJVWGRCRTcyMmtlWXd6TEFvUWp2M2F4NExi
      dmczK1lqS09DQVJRd2dnRVEKTUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCUjFwd243WDZvYQp5aXorT3VzQ0Q5ZThwMkJFTGpBZkJnTlZIU01FR0RB
      V2dCU0N6KzgrUlhkYUdUWUhPUURnVmIxVFE3eDBvREFrCkJnTlZIUkVFSFRBYmdobGpZUzEwYjI5
      c2N5MDNOR1EwWmpVMlpHTTFMV2RuZW1Sak1JR0pCZ2dxQXdRRkJnY0kKQVFSOWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aU9pSjBjblZsSWl3aQphR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSWlMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQnpkWEJ3
      CmJIbGphR0ZwYmkxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSUtvWkl6ajBF
      QXdJRFJ3QXcKUkFJZ1pLVnpSQzJZQ0pQOG13blNmS3FOZStZZWNiQmZ6dEIzcVFmTXVrUFhwb1FD
      SUNvdlM4bEpuT3RoaUxBMwpRL095Q25NNWVyRXhUYXV1aCt0b1RaUExxdFhqCi0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1Nkr1BS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQVRDQ0FhYWdBd0lCQWdJVVUwdU9hQUJpTy94bTBESnpkRTRzNjdCbGRuVXdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd05URTRNVFV3T0RFMVdoY05Nall3
      TXpBM01UVXdPREUxV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCTWJvcERrL1lwVU1HalZCRzV5dVFNRWFVVU1tVTFDN21KTUhxdFNaWm9WRTRMSlA2
      aHMrCmFmSWhIREtYT2ZTdkl0SXhzUGlqb0tDTmdpTlkvdUN1ZFJPalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlNDeis4K1JYZGFH
      VFlIT1FEZ1ZiMVRRN3gwb0RBSwpCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUExTHYwZGdDd1RubVNJ
      R0xEV3pPcThVcWpCTkQ2RVdISjA1L3Vla3A1CmY2WUNJUURxWGE3eEY4dktDZGFnNktNb3VlcW40
      YzBWb3FPTWttSnQwUmNrTmtuaTlBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlu
      cyI4CgZBZG1pbnMSLhIkCAESIBIIEgYIARICCAAaFBISCg5zdXBwbHljaGFpbk1TUBABGgZBZG1p
      bnMiOwoLRW5kb3JzZW1lbnQSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoG
      QWRtaW5zIjcKB1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoG
      QWRtaW5zIjcKB1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoG
      QWRtaW5zKgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0
      Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlu
      cxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zGooSCg1Db25zZW5zdXNUeXBl
      EvgREu0RCghldGNkcmFmdBLgEQrJEQoYb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3GtMILS0t
      LS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQXF1Z0F3SUJBZ0lVSEpKWkJpYnZyVHha
      Y2xINDdDdDlEcHpXNWNvd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFO
      QmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQ
      Y21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13
      TlRFNE1UVXdPVEF3V2hjTk1qUXdOVEUzTVRVeE5EQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIK
      TUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxj
      bVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpk
      WEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVEUz
      UnhrUHdPcmxJRDhwVDYyaGJUZGxFWmQKRGgwcXNaWG41Z05BcG1FNUpaNGdPMFNTYXVOWTZpeXVm
      WEE1aDZoQkQ0aGFKOUR6WFNuOUI2eDRrNWZHbzRJQgpNakNDQVM0d0RnWURWUjBQQVFIL0JBUURB
      Z09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJB
      ZjhFQWpBQU1CMEdBMVVkRGdRV0JCUXJsSW8ycC9WaDNNNXV2UXlFdHdsMlVRaUsKVkRBZkJnTlZI
      U01FR0RBV2dCU0N6KzgrUlhkYUdUWUhPUURnVmIxVFE3eDBvREJCQmdOVkhSRUVPakE0Z2hodgpj
      bVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0hHOXlaR1Z5WlhJeExuVndaM0poWkdVdWRY
      Qm5jbUZrClpTNWpiMjB3YkFZSUtnTUVCUVlIQ0FFRVlIc2lZWFIwY25NaU9uc2lhR1l1UVdabWFX
      eHBZWFJwYjI0aU9pSWkKTENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lKdmNtUmxjbVZ5TVM1emRY
      QndiSGxqYUdGcGJpMXVaWFFpTENKbwpaaTVVZVhCbElqb2liM0prWlhKbGNpSjlmVEFLQmdncWhr
      ak9QUVFEQWdOSUFEQkZBaUVBcjNXOG53ZWZoelpMCkxZWDBQeTJsWEpQMVZOS1F4bmZ4Wm5TYjZ0
      aUl6c3NDSUJPaTN3SUY5eE1xN2wxVi9nMzVBeHlZbmRrS00zTTIKY0ZncnRhcEIwZTBwCi0tLS0t
      RU5EIENFUlRJRklDQVRFLS0tLS0KItMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURC
      VENDQXF1Z0F3SUJBZ0lVSEpKWkJpYnZyVHhaY2xINDdDdDlEcHpXNWNvd0NnWUlLb1pJemowRUF3
      SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3
      d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRY
      QndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRFNE1UVXdPVEF3V2hjTk1qUXdOVEUzTVRVeE5E
      QXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRH
      OXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1T
      RXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhr
      ak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVEUzUnhrUHdPcmxJRDhwVDYyaGJUZGxFWmQKRGgwcXNa
      WG41Z05BcG1FNUpaNGdPMFNTYXVOWTZpeXVmWEE1aDZoQkQ0aGFKOUR6WFNuOUI2eDRrNWZHbzRJ
      QgpNakNDQVM0d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndN
      QkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUXJsSW8ycC9W
      aDNNNXV2UXlFdHdsMlVRaUsKVkRBZkJnTlZIU01FR0RBV2dCU0N6KzgrUlhkYUdUWUhPUURnVmIx
      VFE3eDBvREJCQmdOVkhSRUVPakE0Z2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhT
      Q0hHOXlaR1Z5WlhJeExuVndaM0poWkdVdWRYQm5jbUZrClpTNWpiMjB3YkFZSUtnTUVCUVlIQ0FF
      RVlIc2lZWFIwY25NaU9uc2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSWkKTENKb1ppNUZibkp2Ykd4
      dFpXNTBTVVFpT2lKdmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFFpTENKbwpaaTVVZVhC
      bElqb2liM0prWlhKbGNpSjlmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBcjNXOG53ZWZoelpM
      CkxZWDBQeTJsWEpQMVZOS1F4bmZ4Wm5TYjZ0aUl6c3NDSUJPaTN3SUY5eE1xN2wxVi9nMzVBeHlZ
      bmRrS00zTTIKY0ZncnRhcEIwZTBwCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1z
      EAoYASAFKICAgAgaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIq
      Cg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxIN
      CAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5z
      KgZBZG1pbnMSuS8KC0NvbnNvcnRpdW1zEqkvEt4uChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SxC4S
      sRcKD21hbnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1AS
      gQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0N6Q0NBYktnQXdJQkFnSVVSRHJuOHh0
      VUcvUzhWK3NQUHpmQlhiNXJlUkV3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBn
      eER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFR
      S0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kx
      dVpYUXdIaGNOTWpNd05URTRNVFV3T1RNeVdoY05Nall3TXpBM01UVXdPVE15V2pCa01Rc3dDUVlE
      VlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4
      RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1po
      WTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJFSXdMdjNV
      SGZ2ME1zM21rajFzZmFpcW1ldW0yems1YzQrZwovZUszc0tQY3BhQ2Fmb1ZMYWQrL3U5OTlTMUZo
      OWVsTjlWQ1BUc1hJdEExRVNRbGM0d1dqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lE
      VlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUkdIb1ppT0Jvek9xaTEKSHRGZGZMQ0FqaVZh
      cWpBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlBQjdYa1c2R3RLRGhkTTNCZGtkNjJ1ZGlSOQpKL2Zt
      cHVGVldiZUJ5WENnc1FJZ0d6cWRGcEkxaERXK3VVczg0aVpMWm9JczlmTG0xT1YyQytqNDFSV205
      cnc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSURFVENDQXJlZ0F3SUJBZ0lVRGdOek1oeHlSeEFRTThhL3N3d2NaRUY1YnhJd0NnWUlL
      b1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBN
      QTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFC
      Z05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qTXdOVEU0TVRVeE1UQXdX
      aGNOTWpRd05URTNNVFV4TmpBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RF
      VFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJ
      ekFNQmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURW
      UVFEREJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtv
      WkkKemowREFRY0RRZ0FFUmNYdXNzN0ZMb2RHYXEzUXNkZDhZYWx4MmhxR3phbVpQeWRFVkk2SVI3
      U0xHVDZRbEk4ZAp0bXBERGZnTmQwdkFiL0hHdWUyR0NlRGpIQ1ZCUHQ0eXJxT0NBU0l3Z2dFZU1B
      NEdBMVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJURE8w
      NENuSTlNQlBCbTV3UFBKT0VFNXFyeUVqQWYKQmdOVkhTTUVHREFXZ0JSR0hvWmlPQm96T3FpMUh0
      RmRmTENBamlWYXFqQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwNE5HSTFPVGcxTldJMExY
      QTFjV3M1TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElq
      b2lkSEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJX
      RnVkV1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFda
      aApZM1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFR
      REFnTklBREJGCkFpRUEyM0tPTEQvWlJDNW5ESHZQbXd1UWpqd1ErZjVjMEQ3SUh4bkFOcDFhUzlv
      Q0lHZjRzeTQxZS9DdytoTlEKQmR3VXA3UWdWZldiWlE5aFNjNks1VndaN3ZCVQotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQ0N6Q0NBYktnQXdJQkFnSVVSRHJuOHh0VUcvUzhWK3NQUHpmQlhiNXJlUkV3Q2dZ
      SUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURF
      UE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERB
      YUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpNd05URTRNVFV3T1RN
      eVdoY05Nall3TXpBM01UVXdPVE15V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3
      R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdO
      MGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlx
      R1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJFSXdMdjNVSGZ2ME1zM21rajFzZmFpcW1ldW0yems1
      YzQrZwovZUszc0tQY3BhQ2Fmb1ZMYWQrL3U5OTlTMUZoOWVsTjlWQ1BUc1hJdEExRVNRbGM0d1dq
      UWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVk
      RGdRV0JCUkdIb1ppT0Jvek9xaTEKSHRGZGZMQ0FqaVZhcWpBS0JnZ3Foa2pPUFFRREFnTkhBREJF
      QWlBQjdYa1c2R3RLRGhkTTNCZGtkNjJ1ZGlSOQpKL2ZtcHVGVldiZUJ5WENnc1FJZ0d6cWRGcEkx
      aERXK3VVczg0aVpMWm9JczlmTG0xT1YyQytqNDFSV205cnc9Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0
      dXJlck1TUBoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVmYWN0
      dXJlck1TUBABGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9t
      YW51ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoP
      bWFudWZhY3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxKyFgoKY2Fycmllck1TUBKjFhq/FAoDTVNQ
      ErcUEqwUEqkUCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIr
      RENDQVo2Z0F3SUJBZ0lVWjJZd2lEcmtZcGpzOGw4RnhRVHh5cHJBWHNvd0NnWUlLb1pJemowRUF3
      SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3
      d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allY
      SnlhV1Z5TFc1bGREQWVGdzB5Ck16QTFNVGd4TlRFd05UQmFGdzB5TmpBek1EY3hOVEV3TlRCYU1G
      b3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJr
      eHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNt
      bGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUVpBNTBoaUc4d2dC
      V3g0clc2b0hXUUJrenU0TUNkRDY2QVZiRFV1R1NiZU1QZTVOOW5LaDhSNXpoRVBRQWEKZlMxNXBT
      TTU3V1dWQjJyRmcyajlHZnZDbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdF
      Qgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVlN0ZzeGdaUk5kQmtjMjduUGZ0MU1uREJzeFF3Q2dZ
      SUtvWkl6ajBFCkF3SURTQUF3UlFJaEFOQWp6TDVhd1llWlRaMktHVWhxTk44a29TTTFuaWtiMkd0
      U0dXbThIM0prQWlCZVBQZWQKd1lKb1QxN1dqN0hPZmxvZi9EM05MaW50R0UzYWR5Y3BWOFU3aVE9
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlDN1RDQ0FwU2dBd0lCQWdJVVpMcGhpYlVEcXpqNTU1amMxTU5VM2ZmSDBOc3dDZ1lJS29a
      SXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEw
      R0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1
      allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNekExTVRneE5URXlNREJhRncweU5EQTFNVGN4TlRF
      M01EQmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5
      TWIyNWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0
      R0ExVUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhR
      d1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRZ2wvUjZKVnk4T1UyejVsR21vRTF1
      CkQzU0U4bGJtU3czc2F4dHRnaU9oakpwOHhlZlpCejI1NUxCOUlpRTJqSS94WFhjTEYzQnVDT2l5
      Rzc4NHoxZ3EKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FD
      TUFBd0hRWURWUjBPQkJZRQpGS2MveDFzaUlnWmRCa1pGeUoxcWZ3YmZvbHg1TUI4R0ExVWRJd1FZ
      TUJhQUZIdXhiTVlHVVRYUVpITnU1ejM3CmRUSnd3Yk1VTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2
      YjJ4ekxUWmlObVprTkRRME5tUXRhekp4ZWprd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5
      Y3lJNmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1
      UVdabWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9p
      UVdSdGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkK
      S29aSXpqMEVBd0lEUndBd1JBSWdZdUg4QzN1NHhtTkt1eExRckg3RXh4eWcvVVBJSnlIQ3ZYdi9D
      UjIrUTFVQwpJR25wYTlaZm9HV2lOM2Z6V0dsSEJxRDNBYVN1aDF3REN1VXk4dXVxRzVrYgotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVaMll3aURya1lwanM4bDhGeFFUeHlwckFY
      c293Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dG
      UVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTXpBMU1UZ3hOVEV3TlRCYUZ3MHlO
      akF6TURjeE5URXdOVEJhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWti
      MjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdB
      MVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3
      TkMKQUFRWkE1MGhpRzh3Z0JXeDRyVzZvSFdRQmt6dTRNQ2RENjZBVmJEVXVHU2JlTVBlNU45bkto
      OFI1emhFUFFBYQpmUzE1cFNNNTdXV1ZCMnJGZzJqOUdmdkNvMEl3UURBUEJnTlZIUk1CQWY4RUJU
      QURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVWU3RnN4Z1pSTmRCa2My
      N25QZnQxTW5EQnN4UXdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQU5BanpMNWF3WWVaVFoyS0dV
      aHFOTjhrb1NNMW5pa2IyR3RTR1dtOEgzSmtBaUJlUFBlZAp3WUpvVDE3V2o3SE9mbG9mL0QzTkxp
      bnRHRTNhZHljcFY4VTdpUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiMwoH
      UmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0
      ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIq
      EiAIARIcEggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0VuZG9yc2VtZW50
      EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hh
      bm5lbENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1p
      bnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiQKDENhcGFiaWxpdGll
      cxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoG
      QWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaTgoQ
      T3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWluLW5ldDo3MDUwGhcvQ2hh
      bm5lbC9PcmRlcmVyL0FkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIi
      CgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyoGQWRtaW5zGg4KBAoCCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
