apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://98.70.9.151:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIPzA66/QFLSSGO+pamDl+fd+JWCrbdMoo4N7uTEYAP53EqZeCqNeCqBeCngKWggBEAEaBgjG
      s8miBiIKc3lzY2hhbm5lbCpANDg0MWUyODEwZjdmNWI2ZGE0ZjA1YmM2ZjE3YjA3NzRkY2M2MjA3
      ZGYzM2RmNDU2YmUxMjRjMzQyMjc2YWM2MBIaEhgofyyCmTxUXJB48P1mOuNJQFq/43aCK2gSo10K
      oF0SnV0SlysKB09yZGVyZXISiysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVSHZjakl0NTJja2pFc3F5NEZrbGRYRGdHRTA4d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRBek1USTBOVFEzV2hjTk1qWXdNakl3TVRJME5UUTNX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJCQVRX
      UEwvUzZJQTU5TWxXY3phNEpDMnRvN1FBUURWUXE3dkhoVGZMaEtIN0NKOGxEbkwKZU9ETnUwYld1
      eFJiYnRuSlQ4MUpSQWJONk5vSlhHVisveXVqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVEcyTitaejhlMjUyZXFZVHJERFYrUWpB
      SE1zakFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQXpHWTRGSERGdERWNjA5b2J3dlQ0WDF3dzhX
      eG9KTnFaeDZCZlRlbUMKRjl3Q0lHOGd3QkFrUWNxcy9vQXBjL1R6dzcxT0hkZE1kZjNsOVYvSjB0
      bHluNXJLCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVSHllYUhEQi9jUUNYM1Y3VURKVjhOeFhaMlY4d0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRBek1USTBOakF3V2hjTk1q
      UXdOVEF5TVRJMU1UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFcFo0QlpMaGlMSlZxL2toYjQzZ2d6RllHRzBN
      UE9nd0oKUmFSVGhRT0ZYWnJnRENLd0dPZ3AzdWVDTmhVNFFpc0NDSGdRNnFxYWV3cFA3akNGSElP
      MnBLT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJSWElaemk2VnZRCndEcUFGWFFaWm1SWVFXT3QrREFmQmdOVkhTTUVHREFXZ0JU
      RzJOK1p6OGUyNTJlcVlUckREVitRakFITXNqQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      M05HUTBaalUyWkdNMUxUUmthbWh5TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQUlxb2ZkQk5seDFkZUR0b3V5M2d4WE53eXcyZml4UU1TZ0xpSHFSWjFkR3BBaUIy
      eVdFMHJQK0tXOS9QCmZFZUdUUUFIdmhFazM1S042VzFvZTM5SHBFRXF2QT09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVUh2Y2pJdDUyY2tqRXNxeTRGa2xkWERnR0UwOHdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd05UQXpNVEkwTlRRM1doY05Nall3
      TWpJd01USTBOVFEzV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCQkFUV1BML1M2SUE1OU1sV2N6YTRKQzJ0bzdRQVFEVlFxN3ZIaFRmTGhLSDdDSjhs
      RG5MCmVPRE51MGJXdXhSYmJ0bkpUODFKUkFiTjZOb0pYR1YrL3l1alFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlRHMk4rWno4ZTI1
      MmVxWVRyRERWK1FqQUhNc2pBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUF6R1k0RkhERnREVjYw
      OW9id3ZUNFgxd3c4V3hvSk5xWng2QmZUZW1DCkY5d0NJRzhnd0JBa1FjcXMvb0FwYy9Uenc3MU9I
      ZGRNZGYzbDlWL0owdGx5bjVySwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHV3JpdGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRp
      bWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiYK
      DENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlucxqKEgoNQ29uc2Vuc3VzVHlwZRL4
      ERLtEQoIZXRjZHJhZnQS4BEKyREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrTCC0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQkRDQ0FxdWdBd0lCQWdJVVdnMW5pS0hYdG4wWTBr
      THlsTnRvQnp1bVRyZ3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNt
      UmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd05U
      QXpNVEkwTmpBd1doY05NalF3TlRBeU1USTFNVEF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1C
      a0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21W
      eU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhC
      d2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVRkdTRO
      elVCbTc1MG1YS2VCSVFhNHh3YzFOCnZwd1BBM0hoLzNlYW9SVVlGZCs1K0JmOUtMaEZQSVhMMVVh
      MThsNmF4VzZ5R1VwSEVhTXQ5dExpQXZBd280SUIKTWpDQ0FTNHdEZ1lEVlIwUEFRSC9CQVFEQWdP
      b01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4
      RUFqQUFNQjBHQTFVZERnUVdCQlRwMHdWY2pVZEsrdmUyOU5pR3JzRWRZSGxBCm1qQWZCZ05WSFNN
      RUdEQVdnQlRHMk4rWno4ZTI1MmVxWVRyRERWK1FqQUhNc2pCQkJnTlZIUkVFT2pBNGdoaHYKY21S
      bGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NIRzl5WkdWeVpYSXhMblZ3WjNKaFpHVXVkWEJu
      Y21GawpaUzVqYjIwd2JBWUlLZ01FQlFZSENBRUVZSHNpWVhSMGNuTWlPbnNpYUdZdVFXWm1hV3hw
      WVhScGIyNGlPaUlpCkxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSnZjbVJsY21WeU1TNXpkWEJ3
      YkhsamFHRnBiaTF1WlhRaUxDSm8KWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5ZlRBS0JnZ3Foa2pP
      UFFRREFnTkhBREJFQWlCdVVTdGl6cGswMVJvcwpreWszVzZ3RHlqbEY4bUlSNFRxR3hVazFIZ3Z1
      dlFJZ1hhVklzY0lJeXZ1RUx2TXVMN2UrNHBuWXc2OGdsSXh5CmtOMDV0UVlBU2JzPQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCiLTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQkRD
      Q0FxdWdBd0lCQWdJVVdnMW5pS0hYdG4wWTBrTHlsTnRvQnp1bVRyZ3dDZ1lJS29aSXpqMEVBd0l3
      ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dH
      VEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3
      YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd05UQXpNVEkwTmpBd1doY05NalF3TlRBeU1USTFNVEF3
      V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1
      Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3
      SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pP
      UFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVRkdTROelVCbTc1MG1YS2VCSVFhNHh3YzFOCnZwd1BBM0ho
      LzNlYW9SVVlGZCs1K0JmOUtMaEZQSVhMMVVhMThsNmF4VzZ5R1VwSEVhTXQ5dExpQXZBd280SUIK
      TWpDQ0FTNHdEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJC
      Z2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlRwMHdWY2pVZEsr
      dmUyOU5pR3JzRWRZSGxBCm1qQWZCZ05WSFNNRUdEQVdnQlRHMk4rWno4ZTI1MmVxWVRyRERWK1Fq
      QUhNc2pCQkJnTlZIUkVFT2pBNGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NI
      Rzl5WkdWeVpYSXhMblZ3WjNKaFpHVXVkWEJuY21GawpaUzVqYjIwd2JBWUlLZ01FQlFZSENBRUVZ
      SHNpWVhSMGNuTWlPbnNpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpCkxDSm9aaTVGYm5KdmJHeHRa
      VzUwU1VRaU9pSnZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhRaUxDSm8KWmk1VWVYQmxJ
      am9pYjNKa1pYSmxjaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCdVVTdGl6cGswMVJvcwpr
      eWszVzZ3RHlqbEY4bUlSNFRxR3hVazFIZ3Z1dlFJZ1hhVklzY0lJeXZ1RUx2TXVMN2UrNHBuWXc2
      OGdsSXh5CmtOMDV0UVlBU2JzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAK
      GAEgBSiAgIAKGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoG
      QWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgD
      EgkKB1dyaXRlcnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyoG
      QWRtaW5zEr0vCgtDb25zb3J0aXVtcxKtLxLiLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsguErEX
      Cg9tYW51ZmFjdHVyZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEG
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVQXNJUUJIdXVo
      T2VPekpzbmhtK3hNbXpDd0tzd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hE
      ekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtE
      QXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVa
      WFF3SGhjTk1qTXdOVEF6TVRJME56QTRXaGNOTWpZd01qSXdNVEkwTnpBNFdqQmtNUXN3Q1FZRFZR
      UUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZU
      QVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkz
      UjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCS2EwOGFkVU9m
      cEpRQlRLZnRwYUlGaDFydmpPb296VEttNE8KOFJ0Zlp5ZUpxMCt5amdPU3RlcDNiWXA5M2Fha2Zo
      WVZYUzJBU0psaS9rcHI1UU54OC8yalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZS
      MFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlJ3dmRYMnArcXVicGZFCjZZVVJSWmdtbXorbWRq
      QUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpQTcraWs2bG55VjhrZHlmSStQMXhoenRSczUKNEhka2wr
      cWgzQWJ0TkJYV1VBSWhBTUlDVzlZYW1GMitlWjBGL0dIcUNrOTA5bGNOYUV6Y0JoWURVSVpRNWdC
      WgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlERURDQ0FyZWdBd0lCQWdJVWFjcDBOS2k4ckhYcHlRQzNXc0h5bHRLMTdKTXdDZ1lJS29a
      SXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEw
      R0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdO
      VkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nak13TlRBek1USTBOekF3V2hj
      Tk1qUXdOVEF5TVRJMU1qQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRR
      M0xqTTRMemd1TlRRdlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpB
      TUJnTlZCQXNUQldGa2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFR
      RERCWkJaRzFwYmtCdFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJ
      CnpqMERBUWNEUWdBRU1RcG53WW9QOG5hajFFa01HUzNsVHdZR1EzRFNDdE1kazdBRTdOSGIraEtz
      V2ZzTFN6dG4KVWRacW01Z3o2U0t3eUJsKzRWM0htc1RsOVdDM3BJY1lzS09DQVNJd2dnRWVNQTRH
      QTFVZER3RUIvd1FFQXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUnlIKzRm
      d3ZETXhOS2Z2N1JnVllTWXkxS3NrVEFmCkJnTlZIU01FR0RBV2dCUnd2ZFgycCtxdWJwZkU2WVVS
      UlpnbW16K21kakFrQmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDROR0kxT1RnMU5XSTBMVFV5
      ZUhCc01JR1hCZ2dxQXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9p
      ZEhKMVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1
      ZFdaaFkzUjFjbVZ5SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgK
      WTNSMWNtVnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURB
      Z05IQURCRQpBaUJYVHhQZHBhM2FYcU9pd2JGMUxIVHM4Qys1ZUp0OFpaek5UZVJLczZIOFF3SWdS
      U214eG94SDlXM3ZNK1dwCmp1K2prR0NKMGlRL3hEWlV4NmFlSUlTMXMwdz0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVQXNJUUJIdXVoT2VPekpzbmhtK3hNbXpDd0tzd0NnWUlL
      b1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBN
      QTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFC
      Z05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qTXdOVEF6TVRJME56QTRX
      aGNOTWpZd01qSXdNVEkwTnpBNFdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dX
      blZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBk
      WEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdT
      TTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCS2EwOGFkVU9mcEpRQlRLZnRwYUlGaDFydmpPb296VEtt
      NE8KOFJ0Zlp5ZUpxMCt5amdPU3RlcDNiWXA5M2Fha2ZoWVZYUzJBU0psaS9rcHI1UU54OC8yalFq
      QkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERn
      UVdCQlJ3dmRYMnArcXVicGZFCjZZVVJSWmdtbXorbWRqQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFp
      QTcraWs2bG55VjhrZHlmSStQMXhoenRSczUKNEhka2wrcWgzQWJ0TkJYV1VBSWhBTUlDVzlZYW1G
      MitlWjBGL0dIcUNrOTA5bGNOYUV6Y0JoWURVSVpRNWdCWgotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tChoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVy
      ZXJNU1AaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1
      cmVyTVNQGgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1
      cmVyTVNQEAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21h
      bnVmYWN0dXJlck1TUBoGQWRtaW5zKgZBZG1pbnMSthYKCmNhcnJpZXJNU1ASpxYawxQKA01TUBK7
      FBKwFBKtFAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK1RD
      Q0FaNmdBd0lCQWdJVUlYd3pOWThnZFQwQWkwNCt6TW1xdTZjcUEwTXdDZ1lJS29aSXpqMEVBd0l3
      CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dH
      VEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5
      YVdWeUxXNWxkREFlRncweQpNekExTURNeE1qUTRNamxhRncweU5qQXlNakF4TWpRNE1qbGFNRm94
      Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2
      Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxs
      Y2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVMwdmJrQmdVcm9aeEF1
      bU5kdWUzb1RIbCtmUUZCeVZXM01iRXpyWXFSbDdpNlZTS1RTQWRQK1QzcmdWN2U2ClVYTjJvVlpi
      SDl6cSttS1BRVFYrSktqZm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIK
      L3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVcnB4ZnhHOWE4dTVCWG5tdzZIU2VvSnUvNWtjd0NnWUlL
      b1pJemowRQpBd0lEU1FBd1JnSWhBUDFuYStNWmY1ZzdoMlZJK2JLVWZYRmQ0TFJjdnZ5YU9idnJT
      SjJCWXJHUkFpRUEvNkoxCnVvNTRqWEdIMGZiNDBNSUlRWVpsWnhNZFpHdktqb0N3YTZlak9lOD0K
      LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoitggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQzdqQ0NBcFNnQXdJQkFnSVVJMThRUWNUNlhnZVhFTS9hZmZSSi8yNTYzbzh3Q2dZSUtvWkl6
      ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdB
      MVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZ
      UzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTXpBMU1ETXhNalV3TURCYUZ3MHlOREExTURJeE1qVTFN
      REJhTUhneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1i
      MjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RCV0ZrYldsdU1BNEdB
      MVVFQ3hNSFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVEQ5ZkVMLy9yZmtja0lSVGFFZUx0dApC
      WnJuQUE3YlJBaGVuYzJjditEM0RzRXF4bHBjaHRkZ3dhZ01MWEluakFiUFpkbGJkTEx2TllxY1VN
      SmFyakJpCm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01B
      QXdIUVlEVlIwT0JCWUUKRkhtaHNqaXJiNFV6UXNKZ3QwSENPMkJyNXVJZE1COEdBMVVkSXdRWU1C
      YUFGSzZjWDhSdld2THVRVjU1c09oMApucUNiditaSE1DUUdBMVVkRVFRZE1CdUNHV05oTFhSdmIy
      eHpMVFppTm1aa05EUTBObVF0WkhnM2NITXdnWTBHCkNDb0RCQVVHQndnQkJJR0FleUpoZEhSeWN5
      STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lKMGNuVmxJaXdpYUdZdVFX
      Wm1hV3hwWVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaVFX
      UnRhVzVBWTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJCktv
      Wkl6ajBFQXdJRFNBQXdSUUloQUtXSVcxVDNlTXYvM3NTT2ZsOFhIMDBnUnB1dHVEWHNkWlZ4MWl6
      YytpSy8KQWlBNlhpSFUvY3NiSytWRm9xb29MNVNhQWJOREI2dWxCV2RqYW5lejJjQU4wQT09Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlCK1RDQ0FaNmdBd0lCQWdJVUlYd3pOWThnZFQwQWkwNCt6TW1xdTZj
      cUEwTXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJj
      d0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNekExTURNeE1qUTRNamxhRncw
      eU5qQXlNakF4TWpRNE1qbGFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1
      a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJV
      R0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1C
      QndOQwpBQVMwdmJrQmdVcm9aeEF1bU5kdWUzb1RIbCtmUUZCeVZXM01iRXpyWXFSbDdpNlZTS1RT
      QWRQK1QzcmdWN2U2ClVYTjJvVlpiSDl6cSttS1BRVFYrSktqZm8wSXdRREFQQmdOVkhSTUJBZjhF
      QlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVcnB4ZnhHOWE4dTVC
      WG5tdzZIU2VvSnUvNWtjd0NnWUlLb1pJemowRQpBd0lEU1FBd1JnSWhBUDFuYStNWmY1ZzdoMlZJ
      K2JLVWZYRmQ0TFJjdnZ5YU9idnJTSjJCWXJHUkFpRUEvNkoxCnVvNTRqWEdIMGZiNDBNSUlRWVps
      WnhNZFpHdktqb0N3YTZlak9lOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyIz
      CgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1dy
      aXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiNAoGQWRtaW5z
      EioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5kb3JzZW1l
      bnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVD
      aGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0Fk
      bWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hh
      bm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaLQoZQmxvY2tEYXRh
      SGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoS
      Hwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5z
      GiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8zEgAaBkFkbWlucxomChBIYXNoaW5nQWxnb3Jp
      dGhtEhISCAoGU0hBMjU2GgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1p
      bnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJ
      CgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
