apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.244.7.50:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIJ+A5E6Fdsuj17YAPteuVHFdZj2cKL7EVVCW6XjIskHUEqxeCqleCqZeCngKWggBEAEaBgj7
      zc6hBiIKc3lzY2hhbm5lbCpAMDhkMTFlMjUyYTk4ZTRiZWJjZWJmOThlNzRiMGJiY2ZkNzRhNDYz
      NzY1NzZkMTgyYTMzZmQxMjEyNDlkNjQwMRIaEhgCA/b5vi6GpARLwEUsLQgkB9/ijGnstooSqV0K
      pl0So10SlysKB09yZGVyZXISiysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekND
      QWFhZ0F3SUJBZ0lVVVJUdWp6Mkk1TDlHUlZHYjJtUHgrK2QxNkhzd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TkRFd01EVTFNRFExV2hjTk1qWXdNVEk0TURVMU1EUTFX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJEbCt1
      UHlSc0hCdkZUdHFFdEU4VXo3NXIxaWNaWWg0SmxwUVNZL3ovYTd4S0ZhLytwcTIKUm5JaEFlRmV4
      TzVLc1dUdEtRYmdrdzNYOWp6SUdsQnZqYWlqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUmpCVnNSaFB5UVo1MGJLNlhmKzhlUjFl
      eXQwREFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlBdzU0aDdYUDM3SUhha0RqZkYvY2p6Y25zNERP
      SzRKWjBUTXFyV3ZOODMKN2dJZ0k1YStwQXdDeEg2YVF4aGttTkkrWVVaSm9pbVh6aTZBWkc2SDNE
      QVdnTWc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVWjVsOG1zSms1bVEyUDJWUWxKclB5SUc4N2lVd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TkRFd01EVTFOakF3V2hjTk1q
      UXdOREE1TURZd01UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFZ2lrbE1wL3lHN291eUM0OFBnMjRuSFFOcnht
      dnVmcm8KUXo2Ly8zMjZKdnlYRUt2bW1aUkkwT083ZG1hc3FNTnppMXpPS2dlVGlDVnFUU3FnVHR1
      dndxT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJRVTdCS2JQQUIrCnkrcFV3VVVRZ3BlaVpmYUNOekFmQmdOVkhTTUVHREFXZ0JS
      akJWc1JoUHlRWjUwYks2WGYrOGVSMWV5dDBEQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qbG1ZMlptWkdSakxUYzFkR2huTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQUpBR0FYa3EvNktNb1o0VmhJNzhtYzl4NG5MWlovTWNzQ1J3ajEybWZYUjVBaUF5
      UitDWml1L2RScCtMCkUzOHBTSFF4NHZ0Q01QbjFUQ2ViUFpkSCtFMit1Zz09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlCL3pDQ0FhYWdBd0lCQWdJVVVSVHVqejJJNUw5R1JWR2IybVB4KytkMTZIc3dDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd05ERXdNRFUxTURRMVdoY05Nall3
      TVRJNE1EVTFNRFExV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCRGwrdVB5UnNIQnZGVHRxRXRFOFV6NzVyMWljWlloNEpscFFTWS96L2E3eEtGYS8r
      cHEyClJuSWhBZUZleE81S3NXVHRLUWJna3czWDlqeklHbEJ2amFpalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlJqQlZzUmhQeVFa
      NTBiSzZYZis4ZVIxZXl0MERBSwpCZ2dxaGtqT1BRUURBZ05IQURCRUFpQXc1NGg3WFAzN0lIYWtE
      amZGL2NqemNuczRET0s0SlowVE1xcld2TjgzCjdnSWdJNWErcEF3Q3hINmFReGhrbU5JK1lVWkpv
      aW1Yemk2QVpHNkgzREFXZ01nPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHV3JpdGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRp
      bWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiYK
      DENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlucxqKEgoNQ29uc2Vuc3VzVHlwZRL4
      ERLtEQoIZXRjZHJhZnQS4BEKyREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrTCC0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQlRDQ0FxdWdBd0lCQWdJVVY4b3ZjRzhPbENwQXNO
      VFVoajRsb3FVNlNGY3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNt
      UmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd05E
      RXdNRFUxTmpBd1doY05NalF3TkRBNU1EWXdNVEF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1C
      a0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21W
      eU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhC
      d2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFEYTFu
      YW5xN1N0Q21HS05peEtOQUNCVHlZCmQ0cVI2MVRrd0krZzV6ZWlRVlFZUUxSTUFwak1jUmN6THlw
      T3lMQlB5S2RKVzJlZXZOeUY4RlM0b3VDdm80SUIKTWpDQ0FTNHdEZ1lEVlIwUEFRSC9CQVFEQWdP
      b01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4
      RUFqQUFNQjBHQTFVZERnUVdCQlNCSno2VWFBWDJ5SzVPRitHaVFFT1NESjdMCm96QWZCZ05WSFNN
      RUdEQVdnQlJqQlZzUmhQeVFaNTBiSzZYZis4ZVIxZXl0MERCQkJnTlZIUkVFT2pBNGdoaHYKY21S
      bGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NIRzl5WkdWeVpYSXhMblZ3WjNKaFpHVXVkWEJu
      Y21GawpaUzVqYjIwd2JBWUlLZ01FQlFZSENBRUVZSHNpWVhSMGNuTWlPbnNpYUdZdVFXWm1hV3hw
      WVhScGIyNGlPaUlpCkxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSnZjbVJsY21WeU1TNXpkWEJ3
      YkhsamFHRnBiaTF1WlhRaUxDSm8KWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5ZlRBS0JnZ3Foa2pP
      UFFRREFnTklBREJGQWlFQW9kTkFCb05va2Y5Qgo5eExMd1Y1ZUV6MGIzb2pSSk5GdmJGWjFpWWdB
      T00wQ0lIR1ZrMGlleEN3ZFE5SVErZExMdWJpU0VUUXhUQjF5CitsbERhS09QNC9lVAotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCiLTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQlRD
      Q0FxdWdBd0lCQWdJVVY4b3ZjRzhPbENwQXNOVFVoajRsb3FVNlNGY3dDZ1lJS29aSXpqMEVBd0l3
      ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dH
      VEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3
      YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd05ERXdNRFUxTmpBd1doY05NalF3TkRBNU1EWXdNVEF3
      V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1
      Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3
      SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pP
      UFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFEYTFuYW5xN1N0Q21HS05peEtOQUNCVHlZCmQ0cVI2MVRr
      d0krZzV6ZWlRVlFZUUxSTUFwak1jUmN6THlwT3lMQlB5S2RKVzJlZXZOeUY4RlM0b3VDdm80SUIK
      TWpDQ0FTNHdEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJC
      Z2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNCSno2VWFBWDJ5
      SzVPRitHaVFFT1NESjdMCm96QWZCZ05WSFNNRUdEQVdnQlJqQlZzUmhQeVFaNTBiSzZYZis4ZVIx
      ZXl0MERCQkJnTlZIUkVFT2pBNGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NI
      Rzl5WkdWeVpYSXhMblZ3WjNKaFpHVXVkWEJuY21GawpaUzVqYjIwd2JBWUlLZ01FQlFZSENBRUVZ
      SHNpWVhSMGNuTWlPbnNpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpCkxDSm9aaTVGYm5KdmJHeHRa
      VzUwU1VRaU9pSnZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhRaUxDSm8KWmk1VWVYQmxJ
      am9pYjNKa1pYSmxjaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQW9kTkFCb05va2Y5Qgo5
      eExMd1Y1ZUV6MGIzb2pSSk5GdmJGWjFpWWdBT00wQ0lIR1ZrMGlleEN3ZFE5SVErZExMdWJpU0VU
      UXhUQjF5CitsbERhS09QNC9lVAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAK
      GAEgBSiAgIAKGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoG
      QWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgD
      EgkKB1dyaXRlcnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyoG
      QWRtaW5zEsMvCgtDb25zb3J0aXVtcxKzLxLoLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEs4uErsX
      Cg9tYW51ZmFjdHVyZXJNU1ASpxcarxUKA01TUBKnFRKcFRKZFQoPbWFudWZhY3R1cmVyTVNQEoYG
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNEVENDQWJLZ0F3SUJBZ0lVSStpcHdad3Bl
      R1RZQjFRaHdUWFhuV3dlTGljd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hE
      ekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtE
      QXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVa
      WFF3SGhjTk1qTXdOREV3TURVMU1qQXhXaGNOTWpZd01USTRNRFUxTWpBeFdqQmtNUXN3Q1FZRFZR
      UUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZU
      QVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkz
      UjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCUGZNenVYeVp2
      U0lTSk9vUHREQ3pJeGhjT1lGb05NYnNvbDYKS1htdWdzVlFTRUJla0JDK2plQmVTcEp0L0oraWZV
      S0U0QytKTFd0VUxlaUJDNXJrN01xalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZS
      MFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlRCdkJ4cWdUSnd4TE5yCm13Rm5weHlSbmNOVGdU
      QUtCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUFzMW1wdTJZK0NZeDJ4bjRjem80eS9RWGgKclpOV29u
      TWJJYWE0cnB3bjdPY0NJUUQzN29kUmdwTVUvQk9zbGdPWDBXb0g3Y21UUVJnekg5OStESWZSRTdp
      TApHdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSURFVENDQXJlZ0F3SUJBZ0lVVXRjQVAwRnA3enA1M1k1OFZuLzl1OFZZMkJBd0Nn
      WUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFE
      RVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhE
      QWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qTXdOREV3TURVMU9E
      QXdXaGNOTWpRd05EQTVNRFl3TXpBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJB
      Y1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpY
      SXhJekFNQmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhR
      WURWUVFEREJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZ
      SUtvWkkKemowREFRY0RRZ0FFdEhMUTBuTEs0M2pGK3NRY05Oa3NYNW5hTUFRYndqbFpMb2NNa0dh
      dS8vUTNaalNtbXdZaApLdUttSTU2N05mZUFoOEtBcGVpUzRTeWNUaEFwcFpYaVFLT0NBU0l3Z2dF
      ZU1BNEdBMVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJT
      d0J5c0VtZTAybVl1K3lwTnIrUnoycDlkREpqQWYKQmdOVkhTTUVHREFXZ0JUQnZCeHFnVEp3eExO
      cm13Rm5weHlSbmNOVGdUQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwM1ptTmtZMlptTm1K
      a0xXczNiWEJ4TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1s
      MElqb2lkSEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpv
      aWJXRnVkV1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1
      ZFdaaApZM1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pP
      UFFRREFnTklBREJGCkFpRUErSzB5Y3dQbklZd1B5Ulo5OGdnVmRXTTMzZThhb3pjbjZ2ZExwaVdM
      dDZrQ0lFOHRucEM1ZkRGa1krc00Ka21VbFgxQmJ5MGJDWlloeUEwTUUzQnFCZkZIUgotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKhgYtLS0tLUJFR0lOIENFUlRJRklD
      QVRFLS0tLS0KTUlJQ0RUQ0NBYktnQXdJQkFnSVVJK2lwd1p3cGVHVFlCMVFod1RYWG5Xd2VMaWN3
      Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxq
      YURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4
      SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpNd05ERXdNRFUx
      TWpBeFdoY05Nall3TVRJNE1EVTFNakF4V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVF
      Q0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZt
      WVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcK
      QnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJQZk16dVh5WnZTSVNKT29QdERDekl4aGNPWUZv
      Tk1ic29sNgpLWG11Z3NWUVNFQmVrQkMramVCZVNwSnQvSitpZlVLRTRDK0pMV3RVTGVpQkM1cms3
      TXFqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdB
      MVVkRGdRV0JCVEJ2QnhxZ1RKd3hMTnIKbXdGbnB4eVJuY05UZ1RBS0JnZ3Foa2pPUFFRREFnTkpB
      REJHQWlFQXMxbXB1MlkrQ1l4MnhuNGN6bzR5L1FYaApyWk5Xb25NYklhYTRycHduN09jQ0lRRDM3
      b2RSZ3BNVS9CT3NsZ09YMFdvSDdjbVRRUmd6SDk5K0RJZlJFN2lMCkd3PT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoP
      bWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEK
      D21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMK
      D21hbnVmYWN0dXJlck1TUBABGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARIC
      CAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyoGQWRtaW5zErIWCgpjYXJyaWVyTVNQEqMW
      Gr8UCgNNU1AStxQSrBQSqRQKCmNhcnJpZXJNU1AS6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVYbWliZThOUGVpMXduMFYwTjhiQXFNdWs3d3d3Q2dZSUtv
      Wkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERB
      NWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTXpBME1UQXdOVFV6TWpCYUZ3MHlOakF4TWpnd05U
      VXpNakJhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJn
      TlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1ky
      RXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFTUjhJ
      ZHI1d0ViYnNwNG9reHFvVlpqK09md3hHNmhxa3V4SDMwRU00aFpRdXpwTk0zZ1NxdXpWMVdCQ3Fq
      UgpZcDVLbHEyMDhGaWlqL0htZ3ZLdFJPZFFvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0
      R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVTFkWW5kK1J0dUM1SytDTDNQZ2xUM2I5
      bm9ZUXdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUlnY1BUTnFDUUkwN2dvcXJPMmJ4S0hhdFB3eWxo
      SmU3Mmw3ZTdRVytNNUlpMENJUUNPNGZ3SwpZSlVJMGM5dUJRczdrSFNCUC8zZGI5Y1ErNzFudjFj
      bldCUUIzZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIrIILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSUM3VENDQXBTZ0F3SUJBZ0lVUFRvU0cxZlBZT3N0TEU5UjJYZ3ArN1BEQVRV
      d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZ
      RFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck16QTBNVEF3TlRVNU1EQmFGdzB5TkRB
      ME1Ea3dOakEwTURCYU1IZ3hDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4
      dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCME5oY25KcFpYSXhIakFNQmdOVgpCQXNUQldG
      a2JXbHVNQTRHQTFVRUN4TUhZMkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1QVkyRnljbWxs
      CmNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVM0UVBHZ1o5eWFGTDIz
      Z3o3ek8zWWYKRHZ6WnU4QmVjcDVvQ20zeldLMFlRRXR2a3BsU3NDYkJnVTFjcjVlbUFXc1p1MUFE
      TlJhYnZOQVFDam8rdVErSwpvNElCR0RDQ0FSUXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVk
      RXdFQi93UUNNQUF3SFFZRFZSME9CQllFCkZDb3ZWVW1xMzR0VVJzVDRHOGFtVVlLeC8wVXBNQjhH
      QTFVZEl3UVlNQmFBRk5YV0ozZmtiYmd1U3ZnaTl6NEoKVTkyL1o2R0VNQ1FHQTFVZEVRUWRNQnVD
      R1dOaExYUnZiMnh6TFRkaU5UWTVPRFk0TlRZdE9UaGlOSFF3Z1kwRwpDQ29EQkFVR0J3Z0JCSUdB
      ZXlKaGRIUnljeUk2ZXlKaFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpCk9pSjBjblZs
      SWl3aWFHWXVRV1ptYVd4cFlYUnBiMjRpT2lKallYSnlhV1Z5SWl3aWFHWXVSVzV5YjJ4c2JXVnUK
      ZEVsRUlqb2lRV1J0YVc1QVkyRnljbWxsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlm
      WDB3Q2dZSQpLb1pJemowRUF3SURSd0F3UkFJZ0p6cERVV3JKNlNvL3kvZ0YwQjdzUGVudFJBL0t4
      bmJHRDk1YTV1bmlRMG9DCklHT2h6eWF5MjltZ3dWYW5kQmZwQWNSR3M3WHArbkFKeExsWjcyWk1D
      c0pkCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVVhtaWJlOE5QZWkxd24wVjBO
      OGJBcU11azd3d3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZC
      QWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlh
      V1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNekEwTVRBd05UVXpN
      akJhRncweU5qQXhNamd3TlRVek1qQmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlE
      QVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNq
      RVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhr
      ak9QUU1CQndOQwpBQVNSOElkcjV3RWJic3A0b2t4cW9WWmorT2Z3eEc2aHFrdXhIMzBFTTRoWlF1
      enBOTTNnU3F1elYxV0JDcWpSCllwNUtscTIwOEZpaWovSG1ndkt0Uk9kUW8wSXdRREFQQmdOVkhS
      TUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVMWRZbmQr
      UnR1QzVLK0NMM1BnbFQzYjlub1lRd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdjUFROcUNRSTA3
      Z29xck8yYnhLSGF0UHd5bGhKZTcybDdlN1FXK001SWkwQ0lRQ080ZndLCllKVUkwYzl1QlFzN2tI
      U0JQLzNkYjljUSs3MW52MWNuV0JRQjNnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFk
      bWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5z
      IjQKBkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcK
      C0VuZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMK
      B1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlu
      cxpAChVDaGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRl
      cmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIA
      GhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFz
      aGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1
      Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIx
      LnN1cHBseWNoYWluLW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomCgxDYXBhYmls
      aXRpZXMSFhIMCgoKBlYxXzRfMxIAGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxAC
      GgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIX
      Eg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
