apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.244.7.50:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIBLJrM05xuajqExBUbbplpKwC+nlzw3s9TZ/KGRSm/MSEqZeCqNeCqBeCngKWggBEAEaBgic
      obWhBiIKc3lzY2hhbm5lbCpAY2FmZmFiYWI2OTE4YmJkOGFkMzM0M2I3MDVhZDhjYjU2NTM3MWU3
      ZWY3MzZhZDQyZTliMTA3MzIzNzI5ZjAzNBIaEhiK3AwSfPnbsqsAHTeWCI1573WJSh5kC/ESo10K
      oF0SnV0SuS8KC0NvbnNvcnRpdW1zEqkvEt4uChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SxC4SsRcK
      D21hbnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0N6Q0NBYktnQXdJQkFnSVVkRm1Sek05c2x2
      Mk11emJ1UTlVN3pBUTk2eXd3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RB
      eE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpY
      UXdIaGNOTWpNd05EQTFNVEF5T1RVd1doY05Nall3TVRJek1UQXlPVFV3V2pCa01Rc3dDUVlEVlFR
      RwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRB
      VEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNS
      MWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJIWld4RDhMSXlh
      VXdhY285L2FSdGE2d0M5M2l1QTJzTThhdQpGQndXRFBYZnJvbUhBc0RrU21USitmTlRJZUQ3b1ZG
      YXcrbmNXVEl2c0JaU0VGSlVOQTJqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIw
      UEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUUNQdjhhMDhtRE9CeFIKR1lzYWNiOHg2SjJPb2pB
      S0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCSmJ4L1JYRitoTm9VL1cvMTFEdFI4cFppVgoyaXRsYWx2
      NzgrVHRlaVNTVVFJZ0VVZXFLb2JleExDRHVSSVpxWlBpdVZKQUJubFRDMXNGTkVBTjNIbzVaam89
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSURFVENDQXJlZ0F3SUJBZ0lVRys3UWpib3Zlc3ZUNjBPbmgrdHV0dHNOUnBnd0NnWUlLb1pJ
      emowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBH
      QTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05W
      QkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qTXdOREExTVRBek5qQXdXaGNO
      TWpRd05EQTBNVEEwTVRBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEz
      TGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFN
      QmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFE
      REJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkK
      emowREFRY0RRZ0FFbGtIUGxGeGZhNjhGREpkY1ZiRUtRb2pQYXNtYkZnY0p3L2NVRHB0eHVQTlBz
      dlV5L0QvTApBcE1wWUxnUHk0aEgwR29ibjV3QTZuM05pL1FtQzdBZ3hhT0NBU0l3Z2dFZU1BNEdB
      MVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJRbHoyLzNO
      cWpQeUJUQ1hpcTNjTk5xdmI2K05UQWYKQmdOVkhTTUVHREFXZ0JRQ1B2OGEwOG1ET0J4UkdZc2Fj
      Yjh4NkoyT29qQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwM1ptTmtZMlptTm1Ka0xXNXla
      SFI0TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lk
      SEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVk
      V1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZ
      M1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFn
      TklBREJGCkFpRUErVDNMdUNKRDYzZzFTbitkN0d4bmFWQm1TRmVwa0wwTjBGYzcrclpPNFNvQ0lC
      Z3o4cUZYY3pvbXdpUHEKTVhSOEFzemp5QkRqNnR2bTduTjVhYzJWSnhEKwotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQ0N6Q0NBYktnQXdJQkFnSVVkRm1Sek05c2x2Mk11emJ1UTlVN3pBUTk2eXd3Q2dZSUtv
      Wkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJn
      TlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpNd05EQTFNVEF5T1RVd1do
      Y05Nall3TVRJek1UQXlPVFV3V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1du
      VnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRY
      SmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NN
      NDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJIWld4RDhMSXlhVXdhY285L2FSdGE2d0M5M2l1QTJzTThh
      dQpGQndXRFBYZnJvbUhBc0RrU21USitmTlRJZUQ3b1ZGYXcrbmNXVEl2c0JaU0VGSlVOQTJqUWpC
      QU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdR
      V0JCUUNQdjhhMDhtRE9CeFIKR1lzYWNiOHg2SjJPb2pBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlC
      SmJ4L1JYRitoTm9VL1cvMTFEdFI4cFppVgoyaXRsYWx2NzgrVHRlaVNTVVFJZ0VVZXFLb2JleExD
      RHVSSVpxWlBpdVZKQUJubFRDMXNGTkVBTjNIbzVaam89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJl
      ck1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVy
      ZXJNU1AaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVy
      ZXJNU1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFu
      dWZhY3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxKyFgoKY2Fycmllck1TUBKjFhq/FAoDTVNQErcU
      EqwUEqkUCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrREND
      QVo2Z0F3SUJBZ0lVRWtkeEhLMFNwcVJ3UmFxTHh5TXNWMzRWM3ZVd0NnWUlLb1pJemowRUF3SXcK
      V2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlh
      V1Z5TFc1bGREQWVGdzB5Ck16QTBNRFV4TURNeE1EaGFGdzB5TmpBeE1qTXhNRE14TURoYU1Gb3hD
      ekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZi
      bVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxj
      aTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUjAyV0JpS0ZTdU5ORWFj
      MVFLWkM3WkxFUG94YXBKSWtmR3dFWE9RVFNJSmkzMWQ5OUU5c2dGU1RzVHRWa0cKc1RRcS85UUhF
      Unl6eHQ1bWNkWFJuTzFGbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgov
      d1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVWUG12MmhCajNma3BnVFhZdGhRWkloOTlPNDR3Q2dZSUtv
      Wkl6ajBFCkF3SURTQUF3UlFJZ2J0ZnBhNUM5ZXZNOWMxeDcvMVBJTHJ5bkVTZmVIM2lvOEdiL2Mz
      R0ZycDBDSVFDUmtvY2cKODVhQmVadG5zSEkrcWRka3l3R2h6SFdEUEFBSUNMakFMeHVoa2c9PQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlDN1RDQ0FwU2dBd0lCQWdJVUNHY2RlRWVQVGVwQXVFQ1lqNmVXbk1zN0xWSXdDZ1lJS29aSXpq
      MEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allT
      NWpZWEp5YVdWeUxXNWxkREFlRncweQpNekEwTURVeE1ETTNNREJhRncweU5EQTBNRFF4TURReU1E
      QmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIy
      NWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0Ex
      VUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dU
      QVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUaHlQZ0k1bTc0ZEFSUHFmSUxEUjV3ClIv
      RW5nQTBjeVdCckpqRDdML0pXbzNmSVlxRlk4NFFIYlhBZ0FML3hoOGpuTHlidEY4elRJaHRMU2VC
      enFmUDUKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFB
      d0hRWURWUjBPQkJZRQpGQlYwUjNSckFUbmdOZzl5dXovZnVkdkRuNVVnTUI4R0ExVWRJd1FZTUJh
      QUZGVDVyOW9RWTkzNUtZRTEyTFlVCkdTSWZmVHVPTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4
      ekxUZGlOVFk1T0RZNE5UWXRlSGhpT0dzd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdS
      dGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29a
      SXpqMEVBd0lEUndBd1JBSWdDZHFaTjFIeWtOd0wwZXVEU1pVMW9IOEJ6QWlBNTFsazF1MkozRC9t
      UnRFQwpJQXFQTDhlaVN6RjE5Y01SMmtGT2lqUlB1aXB2dkptYmJNbXVtbnNOb1RVSwotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJRklD
      QVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVFa2R4SEswU3BxUndSYXFMeHlNc1YzNFYzdlV3
      Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2
      YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlE
      VlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTXpBME1EVXhNRE14TURoYUZ3MHlOakF4
      TWpNeE1ETXhNRGhhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4
      RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVF
      QXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMK
      QUFSMDJXQmlLRlN1Tk5FYWMxUUtaQzdaTEVQb3hhcEpJa2ZHd0VYT1FUU0lKaTMxZDk5RTlzZ0ZT
      VHNUdFZrRwpzVFFxLzlRSEVSeXp4dDVtY2RYUm5PMUZvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURB
      UUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVVZQbXYyaEJqM2ZrcGdUWFl0
      aFFaSWg5OU80NHdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUlnYnRmcGE1Qzlldk05YzF4Ny8xUElM
      cnluRVNmZUgzaW84R2IvYzNHRnJwMENJUUNSa29jZwo4NWFCZVp0bnNISStxZGRreXdHaHpIV0RQ
      QUFJQ0xqQUx4dWhrZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiMwoHV3Jp
      dGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyI0CgZBZG1pbnMS
      KhIgCAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNlbWVu
      dBIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdSZWFkZXJzEigS
      HggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5l
      bENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMq
      Fy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwv
      T3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zEpsrCgdPcmRlcmVyEo8rEtIW
      Cg5zdXBwbHljaGFpbk1TUBK/FhrLFAoDTVNQEsMUErgUErUUCg5zdXBwbHljaGFpbk1TUBL1BS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDQVRDQ0FhYWdBd0lCQWdJVWZYMkNaajhRaVdB
      bEtkUXZZdnlhUDNUSFh4d3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpN
      d05EQTFNVEF5T0RNd1doY05Nall3TVRJek1UQXlPRE13V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQ
      Ck1BMEdBMVVFQ0F3R1RHOXVaRzl1TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9N
      QjA5eVpHVnkKWlhJeEd6QVpCZ05WQkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1H
      QnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCQ1l2WEV5SG9mWEVhU1VhcjNnSEVGV2JEMSt2
      Nys1b2tNcElURStkcHZkQmI1Wm9BREluCnh3YndiNkljZTR4U2NJYkUvSUJFbEVISmtvWGtaUXRu
      T3NhalFqQkFNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBH
      QTFVZERnUVdCQlNmV1BJODdDUFRlM0FjY1k3V01uc29RbjNCTGpBSwpCZ2dxaGtqT1BRUURBZ05K
      QURCR0FpRUF3d1VjZWNRYTMzeEVtVXIvWmNvNlg4ODd0MDB3RXd1R0xPMVRYUGVOCkFwVUNJUUQ4
      QnRPSjByL3ZYUDQ5S2Q3YTA2OE41bzFEUkdRcnAwTWI3cERDdUtZOVJ3PT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoioggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzRUQ0NBb2ln
      QXdJQkFnSVVJNWdVa2dya1dncWxQYy8ramQxai9mUzhZMkl3Q2dZSUtvWkl6ajBFQXdJdwpYakVM
      TUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGph
      R0ZwYmkxdVpYUXcKSGhjTk1qTXdOREExTVRBek5EQXdXaGNOTWpRd05EQTBNVEF6T1RBd1dqQnNN
      UXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVN
      UkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUTR3CkRBWURWUVFMRXdWaFpHMXBiakVlTUJ3R0ExVUVB
      d3dWUVdSdGFXNUFjM1Z3Y0d4NVkyaGhhVzR0Ym1WME1Ga3cKRXdZSEtvWkl6ajBDQVFZSUtvWkl6
      ajBEQVFjRFFnQUVrVlRWMUhIR2ZRT0NrWE0zNDlQZnBuV2ZiVXkxazVPbAp3MjNkWUl2TnZ1WU94
      My84MDFGYVdGajU3Z2R1bjlRN0lHeThaN2VMQkM5UVNiWHVHV29VMHFPQ0FSUXdnZ0VRCk1BNEdB
      MVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJ5KzJPd2pU
      MlAKQmNTVWlGTW1MNlh4aW9sOERUQWZCZ05WSFNNRUdEQVdnQlNmV1BJODdDUFRlM0FjY1k3V01u
      c29RbjNCTGpBawpCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAxTmpsbVkyWm1aR1JqTFd0dVlq
      YzVNSUdKQmdncUF3UUZCZ2NJCkFRUjlleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNu
      VmxJaXdpWVdSdGFXNGlPaUowY25WbElpd2kKYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpTENKb1pp
      NUZibkp2Ykd4dFpXNTBTVVFpT2lKQlpHMXBia0J6ZFhCdwpiSGxqYUdGcGJpMXVaWFFpTENKb1pp
      NVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUlLb1pJemowRUF3SURSd0F3ClJBSWdFRXAvNGltQXNh
      eXdka3ZXV1FrT2VOLzZVM2JrNWJOT1N3cDhVNEhtRGtBQ0lHMEZ2b1RFazYxSDJhVFgKMVh3dkhP
      TFdBa3JCcU05L205eFVSTW1IOEpxdQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEy
      EgZTSEEyNTZK9QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0FUQ0NBYWFnQXdJQkFn
      SVVmWDJDWmo4UWlXQWxLZFF2WXZ5YVAzVEhYeHd3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1S
      QXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkx
      dVpYUXcKSGhjTk1qTXdOREExTVRBeU9ETXdXaGNOTWpZd01USXpNVEF5T0RNd1dqQmVNUXN3Q1FZ
      RFZRUUdFd0pIUWpFUApNQTBHQTFVRUNBd0dURzl1Wkc5dU1ROHdEUVlEVlFRSERBWk1iMjVrYjI0
      eEVEQU9CZ05WQkFvTUIwOXlaR1Z5ClpYSXhHekFaQmdOVkJBTU1FbU5oTG5OMWNIQnNlV05vWVds
      dUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQkNZdlhFeUhvZlhFYVNV
      YXIzZ0hFRldiRDErdjcrNW9rTXBJVEUrZHB2ZEJiNVpvQURJbgp4d2J3YjZJY2U0eFNjSWJFL0lC
      RWxFSEprb1hrWlF0bk9zYWpRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3CkRnWURWUjBQQVFI
      L0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJTZldQSTg3Q1BUZTNBY2NZN1dNbnNvUW4zQkxqQUsKQmdn
      cWhrak9QUVFEQWdOSkFEQkdBaUVBd3dVY2VjUWEzM3hFbVVyL1pjbzZYODg3dDAwd0V3dUdMTzFU
      WFBlTgpBcFVDSVFEOEJ0T0owci92WFA0OUtkN2EwNjhONW8xRFJHUXJwME1iN3BEQ3VLWTlSdz09
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOwoLRW5kb3JzZW1lbnQSLBIiCAES
      HhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcKB1JlYWRlcnMSLBIiCAES
      HhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcKB1dyaXRlcnMSLBIiCAES
      HhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgKBkFkbWlucxIuEiQIARIg
      EggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyoGQWRtaW5zGiIKCUJhdGNo
      U2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1p
      bnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoK
      CgZWMV80XzISABoGQWRtaW5zGooSCg1Db25zZW5zdXNUeXBlEvgREu0RCghldGNkcmFmdBLgEQrJ
      EQoYb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3GtMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSURCRENDQXF1Z0F3SUJBZ0lVWWh3d0MwTUIvNnJkazNJUWFEVXBIeGRKSWpjd0NnWUlL
      b1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBN
      QTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUURE
      QkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TkRBMU1UQXpOREF3V2hjTk1qUXdO
      REEwTVRBek9UQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZM
      VEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZj
      bVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVGtkbjI2Zkc5SUpYRStidVdOVGhiN3c4
      L3YKWGVBWEsrMmtSMkN5ci9RcGw0eVBTNlBzU1o2TTI0Z3cwbFFWNjgzOWFPV3plUVNIaG5reE43
      Q0dVSjVCbzRJQgpNakNDQVM0d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0ND
      c0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JC
      VC81eCtRakpSMWtHR0dwNU5lN1JUNnRWc0kKcmpBZkJnTlZIU01FR0RBV2dCU2ZXUEk4N0NQVGUz
      QWNjWTdXTW5zb1FuM0JMakJCQmdOVkhSRUVPakE0Z2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFH
      RnBiaTF1WlhTQ0hHOXlaR1Z5WlhJeExuVndaM0poWkdVdWRYQm5jbUZrClpTNWpiMjB3YkFZSUtn
      TUVCUVlIQ0FFRVlIc2lZWFIwY25NaU9uc2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSWkKTENKb1pp
      NUZibkp2Ykd4dFpXNTBTVVFpT2lKdmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFFpTENK
      bwpaaTVVZVhCbElqb2liM0prWlhKbGNpSjlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUF2M0kw
      UHM4T0lHWTBiCjB5M3JFNzB2S2FINjFYSk15RVhYZkFSMmtsaGhzQUlnQ1JISVVLQmNnL0Y3QmRZ
      amFyQ0NUa0FvZWxVQTRvci8KZW9qdGdIMjVoOUE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      ItMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQXF1Z0F3SUJBZ0lVWWh3d0Mw
      TUIvNnJkazNJUWFEVXBIeGRKSWpjd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZR
      UUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3Ckho
      Y05Nak13TkRBMU1UQXpOREF3V2hjTk1qUXdOREEwTVRBek9UQXdXakJ4TVFzd0NRWURWUVFHRXdK
      SFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdk
      UGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndO
      Q0FBVGtkbjI2Zkc5SUpYRStidVdOVGhiN3c4L3YKWGVBWEsrMmtSMkN5ci9RcGw0eVBTNlBzU1o2
      TTI0Z3cwbFFWNjgzOWFPV3plUVNIaG5reE43Q0dVSjVCbzRJQgpNakNDQVM0d0RnWURWUjBQQVFI
      L0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdO
      VkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVC81eCtRakpSMWtHR0dwNU5lN1JUNnRWc0kKcmpB
      ZkJnTlZIU01FR0RBV2dCU2ZXUEk4N0NQVGUzQWNjWTdXTW5zb1FuM0JMakJCQmdOVkhSRUVPakE0
      Z2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0hHOXlaR1Z5WlhJeExuVndaM0po
      WkdVdWRYQm5jbUZrClpTNWpiMjB3YkFZSUtnTUVCUVlIQ0FFRVlIc2lZWFIwY25NaU9uc2lhR1l1
      UVdabWFXeHBZWFJwYjI0aU9pSWkKTENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lKdmNtUmxjbVZ5
      TVM1emRYQndiSGxqYUdGcGJpMXVaWFFpTENKbwpaaTVVZVhCbElqb2liM0prWlhKbGNpSjlmVEFL
      QmdncWhrak9QUVFEQWdOSEFEQkVBaUF2M0kwUHM4T0lHWTBiCjB5M3JFNzB2S2FINjFYSk15RVhY
      ZkFSMmtsaGhzQUlnQ1JISVVLQmNnL0Y3QmRZamFyQ0NUa0FvZWxVQTRvci8KZW9qdGdIMjVoOUE9
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAoaBkFkbWlucyIi
      CgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9j
      a1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaJgoQSGFzaGluZ0Fs
      Z29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUS
      EBIGCP////8PGgZBZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBs
      eWNoYWluLW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomCgxDYXBhYmlsaXRpZXMS
      FhIMCgoKBlYxXzRfMxIAGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1p
      bnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoK
      BkFkbWlucxACGgZBZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
