apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://98.70.9.151:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIHvsYsLM5cV8+ZhpY7ew3HZAB7z1LF+jOOxDkcRy/BL/Ep5eCpteCpheCngKWggBEAEaBgjV
      ja2jBiIKc3lzY2hhbm5lbCpAYzQzNDNlODEwOWE3NDdmODNlNzNjNjk1MDJlNjcyYjgyMjYzNGI4
      NzU2OWNmZDZkMDYwMDVhZTIxYmRmOWZmMhIaEhhKpO2MNYc9LbToT4BGkwK9qPIcG8DKP1gSm10K
      mF0SlV0SkSsKB09yZGVyZXIShSsSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVQzY4T3ZYc1UxNkN6OXA0SG9YMGU5Tk0rNmdNd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRJeU1UQXlOakExV2hjTk1qWXdNekV4TVRBeU5qQTFX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJLVlNH
      RHVwLzZRUXRmdFEvQWZrUDVpY0JDNTZST3RWYkppN1YxSFh1bzJYMUFEQ3ljdngKT3FFOWpqMVYy
      YVNTNWIvdURMT0ZWdzBETzY3ZVhQQVF6V21qUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU24zY3l6S1ZSay9Bd3gvWVVYWFZETUhC
      Q25TakFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCQjU1UEh3a0VCc0JudzU2bExBOWplL1F6WStj
      ME9UQWNVNVUxYm5ZQ2QKa3dJaEFNZlkyNUhQVzBieXc3U0psL3hiYWtSTVZCVW9MK2pFUkNBK0l4
      T0Q1SkhECi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVWFVkZW9URVdPOGduYVB6VnhPMWI5cDhhTW1Jd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRJeU1UQXpNakF3V2hjTk1q
      UXdOVEl4TVRBek56QXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFc1BsWVFjem8zdUpDcVlYTS9MOU80R1dFYmh4
      anRVa24KajIxNGY3UlZ1WlZxV2RWcW5GejRmTUpaTjVVOWRTbXJUeWdKSUEyV3g5YlNtck9UMUc1
      akxLT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJSRGxvMkpTYXB6CmRJT0pVL1hPZnByU0Z5THd5REFmQmdOVkhTTUVHREFXZ0JT
      bjNjeXpLVlJrL0F3eC9ZVVhYVkRNSEJDblNqQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      M05HUTBaalUyWkdNMUxYaDBZblEwTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnSDlQT0xzUTNiWTd3ZGJ5V3o1aGxEbm5DeVhTbmJ0UlNQTFpHZmlPejlLMENJSEFQ
      c0h1RDJPMDNPTFNqCnhtYjFSa0xObjNVZ0pXK1JZYTMxRXJqNDlyaFUKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVQzY4T3ZYc1UxNkN6OXA0SG9YMGU5Tk0rNmdNd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRJeU1UQXlOakExV2hjTk1qWXdNekV4
      TVRBeU5qQTFXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJLVlNHRHVwLzZRUXRmdFEvQWZrUDVpY0JDNTZST3RWYkppN1YxSFh1bzJYMUFEQ3ljdngK
      T3FFOWpqMVYyYVNTNWIvdURMT0ZWdzBETzY3ZVhQQVF6V21qUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU24zY3l6S1ZSay9Bd3gv
      WVVYWFZETUhCQ25TakFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCQjU1UEh3a0VCc0JudzU2bExB
      OWplL1F6WStjME9UQWNVNVUxYm5ZQ2QKa3dJaEFNZlkyNUhQVzBieXc3U0psL3hiYWtSTVZCVW9M
      K2pFUkNBK0l4T0Q1SkhECi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOwoLRW5k
      b3JzZW1lbnQSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyoG
      QWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91
      dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJAoMQ2Fw
      YWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxqKEgoNQ29uc2Vuc3VzVHlwZRL4ERLtEQoI
      ZXRjZHJhZnQS4BEKyREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrTCC0tLS0tQkVHSU4g
      Q0VSVElGSUNBVEUtLS0tLQpNSUlEQlRDQ0FxdWdBd0lCQWdJVVFPWHFVNnYvT2J3S1dySHFCZmhh
      YWZkanRySXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdN
      Qmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5
      TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd05USXlNVEF6
      TWpBd1doY05NalF3TlRJeE1UQXpOekF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVF
      QnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcK
      RGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGph
      R0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVJOWCs4VHk3d2Z3
      T244UUFDSnBDbnpKTW9jClMzMzNiZS9SaHhZQm83bTlmZ3pITDQrc3JmV1BhYlNmQWdDSFVMTkhW
      WHM1Zy81Q1I2OXRHMlpTMlZCZ280SUIKTWpDQ0FTNHdEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdB
      MVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFN
      QjBHQTFVZERnUVdCQlNMRGMxbWgwQm9wcG5oVnh3Q29UZ1pFREkyCjdUQWZCZ05WSFNNRUdEQVdn
      QlNuM2N5ektWUmsvQXd4L1lVWFhWRE1IQkNuU2pCQkJnTlZIUkVFT2pBNGdoaHYKY21SbGNtVnlN
      UzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NIRzl5WkdWeVpYSXhMblZ3WjNKaFpHVXVkWEJuY21Gawpa
      UzVqYjIwd2JBWUlLZ01FQlFZSENBRUVZSHNpWVhSMGNuTWlPbnNpYUdZdVFXWm1hV3hwWVhScGIy
      NGlPaUlpCkxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSnZjbVJsY21WeU1TNXpkWEJ3YkhsamFH
      RnBiaTF1WlhRaUxDSm8KWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5ZlRBS0JnZ3Foa2pPUFFRREFn
      TklBREJGQWlFQXAxWjQyY2R2N2FVKwp2WWJuaGtCRUptbWNWUUh2aDVuczFETW5GMkRMUlY4Q0lE
      TzZDczhTaTI0eW9oV0pmSlROMzQyd0RDTGM5UG85CmZ3VTNrVS9yUXVwZQotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCiLTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQlRDQ0FxdWdB
      d0lCQWdJVVFPWHFVNnYvT2J3S1dySHFCZmhhYWZkanRySXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFH
      RnBiaTF1WlhRdwpIaGNOTWpNd05USXlNVEF6TWpBd1doY05NalF3TlRJeE1UQXpOekF3V2pCeE1R
      c3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1S
      QXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZR
      UURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJn
      Z3Foa2pPUFFNQkJ3TkNBQVJOWCs4VHk3d2Z3T244UUFDSnBDbnpKTW9jClMzMzNiZS9SaHhZQm83
      bTlmZ3pITDQrc3JmV1BhYlNmQWdDSFVMTkhWWHM1Zy81Q1I2OXRHMlpTMlZCZ280SUIKTWpDQ0FT
      NHdEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdF
      RgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNMRGMxbWgwQm9wcG5oVnh3
      Q29UZ1pFREkyCjdUQWZCZ05WSFNNRUdEQVdnQlNuM2N5ektWUmsvQXd4L1lVWFhWRE1IQkNuU2pC
      QkJnTlZIUkVFT2pBNGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NIRzl5WkdW
      eVpYSXhMblZ3WjNKaFpHVXVkWEJuY21GawpaUzVqYjIwd2JBWUlLZ01FQlFZSENBRUVZSHNpWVhS
      MGNuTWlPbnNpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpCkxDSm9aaTVGYm5KdmJHeHRaVzUwU1VR
      aU9pSnZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhRaUxDSm8KWmk1VWVYQmxJam9pYjNK
      a1pYSmxjaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQXAxWjQyY2R2N2FVKwp2WWJuaGtC
      RUptbWNWUUh2aDVuczFETW5GMkRMUlY4Q0lETzZDczhTaTI0eW9oV0pmSlROMzQyd0RDTGM5UG85
      CmZ3VTNrVS9yUXVwZQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiA
      gIAIGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5z
      EhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyoGQWRtaW5z
      Er0vCgtDb25zb3J0aXVtcxKtLxLiLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsguErEXCg9tYW51
      ZmFjdHVyZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEGLS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVTmFNVzNxL1hnQWZ6bWk1
      TXNpN3hOczdkOTdnd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdO
      VkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1
      MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhj
      Tk1qTXdOVEl5TVRBeU56STFXaGNOTWpZd016RXhNVEF5TnpJMVdqQmtNUXN3Q1FZRFZRUUcKRXdK
      RFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05W
      QkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5
      TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCREFadHVvUVhOWHdoYUwz
      T00wZkhQSHM1eFBYYXplTi9jK20KQjlhWEtHYmw4VzRLT2ZRNkdVUVpLaE55T3dDbmhKcFI3anlw
      TmRmUjZPL0lnQk8zWDRXalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgv
      QkFRREFnR21NQjBHQTFVZERnUVdCQlE1WG8vR2lvMDFNVFJ5CnpBSU02REJYYTArdXpqQUtCZ2dx
      aGtqT1BRUURBZ05JQURCRkFpRUFnMjZDdUxhT2dQOFhhUklYd3RtTXpTcmIKK2t3Y21LNDYzMEFr
      VmkrTFZsUUNJRmswc3AwVnUzSVVpS2wzbVQ3MkVMS2pUQ3VPbEdHN3lhaDNta1hsM1V5TgotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlE
      RVRDQ0FyZWdBd0lCQWdJVWErcitiSmdjRUQ4cDJ0KzRERnhLYWE4dUhUVXdDZ1lJS29aSXpqMEVB
      d0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVC
      d3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1F
      Mk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nak13TlRJeU1UQXpNekF3V2hjTk1qUXdO
      VEl4TVRBek9EQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRRM0xqTTRM
      emd1TlRRdlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpBTUJnTlZC
      QXNUQldGa2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFRRERCWkJa
      RzFwYmtCdFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJCnpqMERB
      UWNEUWdBRUd5aC95OU9PQ2ladENTWVJucTRWbUJBYlcwWGJhZkRXUlJoeS9jUVh2MGVQNUVnaUxY
      RVEKVGdscjhpNThINERXTmcwbVRma0xYcUdKNzZYdmtXWnU1cU9DQVNJd2dnRWVNQTRHQTFVZER3
      RUIvd1FFQXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCU1R4ZVVudGlIaWZs
      SzlxclJjRVVid1hUTWNHREFmCkJnTlZIU01FR0RBV2dCUTVYby9HaW8wMU1UUnl6QUlNNkRCWGEw
      K3V6akFrQmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDROR0kxT1RnMU5XSTBMWE0wT1hGck1J
      R1hCZ2dxQXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9pZEhKMVpT
      SXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1ZFdaaFkz
      UjFjbVZ5SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgKWTNSMWNt
      VnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05JQURC
      RgpBaUVBbDRZakdDTVhnUTNJbk1CQ01qekdVRE03WFc0TC9QUEtCUG1qWVdYdXFzZ0NJQkNTdnBn
      K2cvVHRXTXh0CkpBVFJ6dmR0MVBiNXBpMG8yNWI5bFUySXlWVTMKLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SUNERENDQWJLZ0F3SUJBZ0lVTmFNVzNxL1hnQWZ6bWk1TXNpN3hOczdkOTdnd0NnWUlLb1pJemow
      RUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFV
      RUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFN
      TUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qTXdOVEl5TVRBeU56STFXaGNOTWpZ
      d016RXhNVEF5TnpJMVdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdO
      b01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pF
      Y01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdF
      R0NDcUdTTTQ5QXdFSEEwSUFCREFadHVvUVhOWHdoYUwzT00wZkhQSHM1eFBYYXplTi9jK20KQjlh
      WEtHYmw4VzRLT2ZRNkdVUVpLaE55T3dDbmhKcFI3anlwTmRmUjZPL0lnQk8zWDRXalFqQkFNQThH
      QTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlE1
      WG8vR2lvMDFNVFJ5CnpBSU02REJYYTArdXpqQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUFnMjZD
      dUxhT2dQOFhhUklYd3RtTXpTcmIKK2t3Y21LNDYzMEFrVmkrTFZsUUNJRmswc3AwVnUzSVVpS2wz
      bVQ3MkVMS2pUQ3VPbEdHN3lhaDNta1hsM1V5TgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoG
      QWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1Aa
      BkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVyZXJNU1AQ
      ARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1
      cmVyTVNQGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0
      dXJlck1TUBoGQWRtaW5zKgZBZG1pbnMSthYKCmNhcnJpZXJNU1ASpxYawxQKA01TUBK7FBKwFBKt
      FAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK1RDQ0FaNmdB
      d0lCQWdJVUhyb3VnSjUxSmljVXJXVy9nNndBM0gwd3IyRXdDZ1lJS29aSXpqMEVBd0l3CldqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxX
      NWxkREFlRncweQpNekExTWpJeE1ESTROREphRncweU5qQXpNVEV4TURJNE5ESmFNRm94Q3pBSkJn
      TlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJq
      RVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpY
      UXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVFsaGdyRmVYMkpaZUpWRVpkdnJR
      WVowekJRcEJQK1lINlpWaWI5c25JVS9INnNiMmdkL1JJNk96dEt2dDFICmtnTVY2MUpTODFjd3NJ
      a1VJZjF6ZlVYSW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3
      SUJwakFkQmdOVkhRNEVGZ1FVZUhQOFJ2OS8zL3BhQ1U4NGxyZU9uUXVYQXpJd0NnWUlLb1pJemow
      RQpBd0lEU1FBd1JnSWhBTEVHUjNqRnV0WXZEblVzaDk1cm82aUh0ZlZENFpzcDgrUkNkL285ZDNy
      SkFpRUE3RHdaCnNackJPL3VxUjA2Wko4SW5YUTYyTjgvZWcyTVF5a1BmS3p3dGt2Zz0KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoitggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzdq
      Q0NBcFNnQXdJQkFnSVVVbUwvZ0ZHRVBwbkdOVitqeU92RUthRERPVkl3Q2dZSUtvWkl6ajBFQXdJ
      dwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3
      R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhK
      eWFXVnlMVzVsZERBZUZ3MHkKTXpBMU1qSXhNRE0yTURCYUZ3MHlOREExTWpFeE1EUXhNREJhTUhn
      eEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0
      eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hN
      SFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdj
      cWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUXE3YTJ2cGRvSmZjM3VrMGtIK0FCNwp3Z09Vc0x4
      aFl6UFZ1QWhqZ3Z2cyt1UXRJU1pySWFQMEEwZVczZEJWZ2tvdFRrOHEzWFZ4cmNOUWZKSVhxOG4z
      Cm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlE
      VlIwT0JCWUUKRklyRTVvRk9qNG9JQTRGZDcrM1VXdTVTRWR0VU1COEdBMVVkSXdRWU1CYUFGSGh6
      L0ViL2Y5LzZXZ2xQT0phMwpqcDBMbHdNeU1DUUdBMVVkRVFRZE1CdUNHV05oTFhSdmIyeHpMVFpp
      Tm1aa05EUTBObVF0YlRocmVIZ3dnWTBHCkNDb0RCQVVHQndnQkJJR0FleUpoZEhSeWN5STZleUpo
      WW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hw
      WVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaVFXUnRhVzVB
      WTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBF
      QXdJRFNBQXdSUUloQUtZUmxTUFpFQ2htY3VoWGN3aXo1K1NEblRFaElpTmJGYUd2a3JKekJtWDkK
      QWlCU2hTQlllTEx6VG1NWEd6YXBoWEYzU0tiUVdPb3VwZnh0RHl5ajJuRG1uZz09Ci0tLS0tRU5E
      IENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlCK1RDQ0FaNmdBd0lCQWdJVUhyb3VnSjUxSmljVXJXVy9nNndBM0gwd3IyRXdD
      Z1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURW
      UVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNekExTWpJeE1ESTROREphRncweU5qQXpN
      VEV4TURJNE5ESmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhE
      ekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVB
      d3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpB
      QVFsaGdyRmVYMkpaZUpWRVpkdnJRWVowekJRcEJQK1lINlpWaWI5c25JVS9INnNiMmdkL1JJNk96
      dEt2dDFICmtnTVY2MUpTODFjd3NJa1VJZjF6ZlVYSW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFR
      SC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVZUhQOFJ2OS8zL3BhQ1U4NGxy
      ZU9uUXVYQXpJd0NnWUlLb1pJemowRQpBd0lEU1FBd1JnSWhBTEVHUjNqRnV0WXZEblVzaDk1cm82
      aUh0ZlZENFpzcDgrUkNkL285ZDNySkFpRUE3RHdaCnNackJPL3VxUjA2Wko4SW5YUTYyTjgvZWcy
      TVF5a1BmS3p3dGt2Zz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI0CgZBZG1p
      bnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNl
      bWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdSZWFkZXJz
      EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1dyaXRlcnMSKBIe
      CAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVs
      Q3JlYXRpb25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoX
      L0NoYW5uZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9P
      cmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRo
      bRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP//
      //8PGgZBZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWlu
      LW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggK
      BFYyXzASABoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFk
      bWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVy
      cxoGQWRtaW5zKgZBZG1pbnMaDgoECgIKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
