apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://52.229.229.54:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIIFmASy/D+Cu37u4JZ87ujS2lOqnJoJ5yM5YIessOuFOEppeCpdeCpReCngKWggBEAEaBgjf
      nMycBiIKc3lzY2hhbm5lbCpAMjEwODYzYWFkMWVhMWU2NTlkZjk5NzBjNjk4MTlhZmY2YzA3NWM5
      YjUxMzBhYTA0ZGJjY2NkNjU0ZTExZDE5MRIaEhjhLHegbKAsAOnGDdpU3q6uBNLPEqVgXsESl10K
      lF0SkV0SkysKB09yZGVyZXIShysSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekND
      QWFhZ0F3SUJBZ0lVT3k1ZkpONzUvMjV1MU1lb3NabkNlRVZhKzFrd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBNU1UQXhOVE13V2hjTk1qVXdPVEk0TVRBeE5UTXdX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJCanZQ
      V0ZSVDJvWStmUUNqc3RpNSs5V0I3cnBtdXREWVVIQjdERlJrVjM4dVZLU1MyNzQKYUM3VEZGOHNU
      ditvd0tqd3VXN3g1ZGJqeGFtS3ZzMFpWQ1dqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVHczTHA5VUd5aXFkZ1Fja05SUHlBcExp
      aERMREFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlCUk12eDdzVTJac0FpMmRZVTRBV0k1RE1TZ0Rx
      YndrMVFVNU9TbjJYbi8KeEFJZ2RISEpvR1Q0L1FiTkdiVkVRTDBsZEFZZGJFWmJ1elJhN241eksv
      ajh3Vm89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVTzZXQ2VWVnpyc1ZLTkxpblVJajh4UFFkM1ZZd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBNU1UQXlNVEF3V2hjTk1q
      TXhNakE1TVRBeU5qQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFNXZWZ0U1WUxHamZnV09XenByUjFFK09xekZ6
      SnhabE4KeklOT3JHSWVXTTVVRlV6S09COVN6aTRwUitBcml4TFBxSmhrTENCODFRako3NUNzblJB
      N1ZLT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJSWUE3ay9zc3M3ClJGMHpFNkd1bXd6RjlnZk8vVEFmQmdOVkhTTUVHREFXZ0JU
      dzNMcDlVR3lpcWRnUWNrTlJQeUFwTGloRExEQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MlltSTRaalprTmpSakxXWnJaM1EwTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnUkxMeG9xdVNiTENWT3BGWHdVNW9hWUpFN293RlhjcURlVEovTHVNdE1PMENJRkRi
      SlB5b0ZlRFZkK29OClRuSGNqSFpWWllCOTNrWG1taHlIVksvU0tXc3MKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUIvekNDQWFhZ0F3SUJBZ0lVT3k1ZkpONzUvMjV1MU1lb3NabkNlRVZhKzFrd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBNU1UQXhOVE13V2hjTk1qVXdPVEk0
      TVRBeE5UTXdXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJCanZQV0ZSVDJvWStmUUNqc3RpNSs5V0I3cnBtdXREWVVIQjdERlJrVjM4dVZLU1MyNzQK
      YUM3VEZGOHNUditvd0tqd3VXN3g1ZGJqeGFtS3ZzMFpWQ1dqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVHczTHA5VUd5aXFkZ1Fj
      a05SUHlBcExpaERMREFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlCUk12eDdzVTJac0FpMmRZVTRB
      V0k1RE1TZ0RxYndrMVFVNU9TbjJYbi8KeEFJZ2RISEpvR1Q0L1FiTkdiVkVRTDBsZEFZZGJFWmJ1
      elJhN241eksvajh3Vm89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiYKDENhcGFiaWxpdGllcxIW
      EgwKCgoGVjFfNF8yEgAaBkFkbWlucxqKEgoNQ29uc2Vuc3VzVHlwZRL4ERLtEQoIZXRjZHJhZnQS
      4BEKyREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrTCC0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlEQlRDQ0FxdWdBd0lCQWdJVU5Ca09iM1BYQU8rS2xXR0ZXc1VBeTQ0V0VMRXdD
      Z1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURW
      UVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1qQTVNVEF5TVRBd1doY05N
      ak14TWpBNU1UQXlOakF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVO
      VEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxF
      d2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpa
      WFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVJRT3V0d0tPUEtyV2NKcG1taVg2
      TzlSbWJFCk1kMzJuUWZtOTdFUEw3S3h2dEJmeE4xMTBNMDJIZ2JHTGdrUHJicy9OaHZwMFdNK3dK
      K3plSWNWQllZc280SUIKTWpDQ0FTNHdEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01C
      UUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERn
      UVdCQlFsenh3U01CWWJyY281bTE0eGlUT3MvTFFaCnhUQWZCZ05WSFNNRUdEQVdnQlR3M0xwOVVH
      eWlxZGdRY2tOUlB5QXBMaWhETERCQkJnTlZIUkVFT2pBNGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JI
      bGphR0ZwYmkxdVpYU0NIRzl5WkdWeVpYSXhMblZ3WjNKaFpHVXVkWEJuY21GawpaUzVqYjIwd2JB
      WUlLZ01FQlFZSENBRUVZSHNpWVhSMGNuTWlPbnNpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpCkxD
      Sm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSnZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhR
      aUxDSm8KWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlF
      QWdpQTg2c284TWVtZApoRjVIRm5jODFXUlQ4eE5RMjVobjJsZUI5bktUekxNQ0lHNzNaN3EzcCtw
      LzMyWHcyRWFOZ2hWQWRBYUNPb3czCjdQZ2oyblRhWHNMMQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCiLTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQlRDQ0FxdWdBd0lCQWdJVU5C
      a09iM1BYQU8rS2xXR0ZXc1VBeTQ0V0VMRXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJo
      TUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0Rn
      WURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhR
      dwpIaGNOTWpJeE1qQTVNVEF5TVRBd1doY05Nak14TWpBNU1UQXlOakF3V2pCeE1Rc3dDUVlEVlFR
      R0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFR
      S0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21S
      bGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFN
      QkJ3TkNBQVJRT3V0d0tPUEtyV2NKcG1taVg2TzlSbWJFCk1kMzJuUWZtOTdFUEw3S3h2dEJmeE4x
      MTBNMDJIZ2JHTGdrUHJicy9OaHZwMFdNK3dKK3plSWNWQllZc280SUIKTWpDQ0FTNHdEZ1lEVlIw
      UEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpB
      TUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlFsenh3U01CWWJyY281bTE0eGlUT3MvTFFa
      CnhUQWZCZ05WSFNNRUdEQVdnQlR3M0xwOVVHeWlxZGdRY2tOUlB5QXBMaWhETERCQkJnTlZIUkVF
      T2pBNGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NIRzl5WkdWeVpYSXhMblZ3
      WjNKaFpHVXVkWEJuY21GawpaUzVqYjIwd2JBWUlLZ01FQlFZSENBRUVZSHNpWVhSMGNuTWlPbnNp
      YUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpCkxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSnZjbVJs
      Y21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhRaUxDSm8KWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5
      ZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQWdpQTg2c284TWVtZApoRjVIRm5jODFXUlQ4eE5R
      MjVobjJsZUI5bktUekxNQ0lHNzNaN3EzcCtwLzMyWHcyRWFOZ2hWQWRBYUNPb3czCjdQZ2oyblRh
      WHNMMQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAKGgZBZG1p
      bnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4S
      BAoCMnMaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5z
      IiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoH
      V3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zKgZBZG1p
      bnMStS8KC0NvbnNvcnRpdW1zEqUvEtouChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SwC4SsRcKD21h
      bnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVERFBaclFSbVRTTWJU
      aUkrTVhaMFFNK0dIS1F3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5C
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5Z
      VzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdI
      aGNOTWpJeE1qQTVNVEF4TmpVd1doY05NalV3T1RJNE1UQXhOalV3V2pCa01Rc3dDUVlEVlFRRwpF
      d0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJn
      TlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNt
      VnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJEK3VDeDhVUWM5T3BI
      MDVnMnhyQndVRldUckR0VUZxOUNEQgpNTXNQYzRObWJCc2RxYmdTaXZ2WGFrMFdqQVl5cm5sVmpE
      TEdaVG5LcDhuNWd4cWtKcG1qUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFR
      SC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUWs3aGlaQUE2ek5sUXkKNitmYldHVVY3dTMrNERBS0Jn
      Z3Foa2pPUFFRREFnTklBREJGQWlBN3FtOCtyWjE3SlZzUXAvWDdJSWV3OW1KegpIOHNOUnRGMGIr
      cHRUb0hQMXdJaEFLVjExL0JYMG5vdDZUQlpId21ycXlmVjE2dzBBcjRhRTYyeWExOW56TFYxCi0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SURFVENDQXJlZ0F3SUJBZ0lVS29mUGJ1dURHemtOTzJpTlVRZEF4TWtvS2kwd0NnWUlLb1pJemow
      RUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFV
      RUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFN
      TUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNakE1TVRBeU16QXdXaGNOTWpN
      eE1qQTVNVEF5T0RBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEzTGpN
      NEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFNQmdO
      VkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFEREJa
      QlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkKemow
      REFRY0RRZ0FFMDhmNzlyaDhnaGdDN2ZxWXdzZ2QzdnV5TkRLSGtjUmdseFFzSEVnTmcvYTVrT1FZ
      UWdtRgphaVRJM3d5RXY3cWwzUitQUnNtRGlHTWp0RVhsM3g2VndxT0NBU0l3Z2dFZU1BNEdBMVVk
      RHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJTOW1SaFYzR2tr
      VWZycmlUeDhCODBiM0RXaHVUQWYKQmdOVkhTTUVHREFXZ0JRazdoaVpBQTZ6TmxReTYrZmJXR1VW
      N3UzKzREQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwMU5UazBOemRtTmpaa0xUaDBibWR1
      TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lkSEox
      WlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVkV1po
      WTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZM1Ix
      Y21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTklB
      REJGCkFpRUFwZWU4dTVsaWZ3S2tUbHhVZkhGZzBRK3JLdDRWdjhEREUxWnc5bzZDWW1jQ0lGM0kw
      THJ6a2ZSMHFQYnEKQmc4OXVlTUxoN1FIcnNPWWJYd3NqdXhYMmZJdgotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQ0REQ0NBYktnQXdJQkFnSVVERFBaclFSbVRTTWJUaUkrTVhaMFFNK0dIS1F3Q2dZSUtvWkl6
      ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdB
      MVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZC
      QU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1qQTVNVEF4TmpVd1doY05N
      alV3T1RJNE1UQXhOalV3V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlh
      V05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxj
      akVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlB
      Z0VHQ0NxR1NNNDlBd0VIQTBJQUJEK3VDeDhVUWM5T3BIMDVnMnhyQndVRldUckR0VUZxOUNEQgpN
      TXNQYzRObWJCc2RxYmdTaXZ2WGFrMFdqQVl5cm5sVmpETEdaVG5LcDhuNWd4cWtKcG1qUWpCQU1B
      OEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JC
      UWs3aGlaQUE2ek5sUXkKNitmYldHVVY3dTMrNERBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlBN3Ft
      OCtyWjE3SlZzUXAvWDdJSWV3OW1KegpIOHNOUnRGMGIrcHRUb0hQMXdJaEFLVjExL0JYMG5vdDZU
      QlpId21ycXlmVjE2dzBBcjRhRTYyeWExOW56TFYxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      GgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVy
      ZXJNU1AaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1
      cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0
      dXJlck1TUBoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVmYWN0
      dXJlck1TUBABGgZBZG1pbnMqBkFkbWlucxKuFgoKY2Fycmllck1TUBKfFhq7FAoDTVNQErMUEqgU
      EqUUCgpjYXJyaWVyTVNQEuUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5ekNDQVo2
      Z0F3SUJBZ0lVSlAwQkZLV0YzdWNYVWtoclc5Z1ppTyttN0N3d0NnWUlLb1pJemowRUF3SXcKV2pF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5
      TFc1bGREQWVGdzB5Ck1qRXlNRGt4TURFNE1EZGFGdzB5TlRBNU1qZ3hNREU0TURkYU1Gb3hDekFK
      QmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2
      YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1
      WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUkZacXViUjZFSXFZM3c4ZnZk
      WTlRaFdaWGNaZzh5VFBqbmJEZFpYZDViaVBXTFFSTExVK2l5bVVuNWMyamYKRTgwYVVHdkpTUzBI
      c3VYRW9BVE42YzYrbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FF
      QXdJQnBqQWRCZ05WSFE0RUZnUVV2MWJkcDAzU2lFYzc4Q09nTTlEdnMyTlhwamN3Q2dZSUtvWkl6
      ajBFCkF3SURSd0F3UkFJZ0JxcE03WFdnK2xBMHhSWWFLYXE0Y29VaktleVpIRkVDSEQ0RjhDeitj
      bm9DSUYrOUtwV3cKMUkxU2U1ZDhSVDNjR2JER0p2SldYNFVZM3V6ZmRKaUFGbmd4Ci0tLS0tRU5E
      IENFUlRJRklDQVRFLS0tLS0KIrYILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3akND
      QXBTZ0F3SUJBZ0lVTllEZU0rQTlyUUF1S1dZY3hpTmJJUzVSeldVd0NnWUlLb1pJemowRUF3SXcK
      V2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlh
      V1Z5TFc1bGREQWVGdzB5Ck1qRXlNRGt4TURJMU1EQmFGdzB5TXpFeU1Ea3hNRE13TURCYU1IZ3hD
      ekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhF
      REFPQmdOVkJBb1RCME5oY25KcFpYSXhIakFNQmdOVgpCQXNUQldGa2JXbHVNQTRHQTFVRUN4TUhZ
      MkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1QVkyRnljbWxsCmNpMXVaWFF3V1RBVEJnY3Fo
      a2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFkMEhrVUlTK1FJTkp1NjZGOXMxSlIKMXc4eWs3R0Q0
      bUU1dEYxZ2o2aTBmQlFEczdMTGJOR2cydUQ5bDNhVzE0eno2Wk8rZ2ZSL2ZBUXFQbjJlUXZKTApv
      NElCR0RDQ0FSUXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZS
      ME9CQllFCkZFWTlrNzlVTGJIRUo3eEwrOWFZWU5pZEh4aUZNQjhHQTFVZEl3UVlNQmFBRkw5VzNh
      ZE4wb2hITy9Bam9EUFEKNzdOalY2WTNNQ1FHQTFVZEVRUWRNQnVDR1dOaExYUnZiMnh6TFRkak5E
      ZGtPVGxpWTJJdFptTmlaemd3Z1kwRwpDQ29EQkFVR0J3Z0JCSUdBZXlKaGRIUnljeUk2ZXlKaFlt
      RmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpCk9pSjBjblZsSWl3aWFHWXVRV1ptYVd4cFlY
      UnBiMjRpT2lKallYSnlhV1Z5SWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2lRV1J0YVc1QVky
      RnljbWxsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSQpLb1pJemowRUF3
      SURTQUF3UlFJaEFOZE9laGxtbUtnMEVyK0pTK3A4Z21uaVVuYWdRdG5lck83bDh6N0VDQmlTCkFp
      QUtxT2gxN29NbjdtK0d6UG1Gc3luS2Q0TzVtMlJDcjJrOVRzdDAyWCs3bUE9PQotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK5QUtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQjl6Q0NBWjZnQXdJQkFnSVVKUDBCRktXRjN1Y1hVa2hyVzlnWmlPK203Q3d3Q2dZ
      SUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFR
      RERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFeU1Ea3hNREU0TURkYUZ3MHlOVEE1TWpn
      eE1ERTRNRGRhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpB
      TkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3
      T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFS
      RlpxdWJSNkVJcVkzdzhmdmRZOVFoV1pYY1pnOHlUUGpuYkRkWlhkNWJpUFdMUVJMTFUraXltVW41
      YzJqZgpFODBhVUd2SlNTMEhzdVhFb0FUTjZjNitvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgv
      TUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVXYxYmRwMDNTaUVjNzhDT2dNOUR2
      czJOWHBqY3dDZ1lJS29aSXpqMEUKQXdJRFJ3QXdSQUlnQnFwTTdYV2crbEEweFJZYUthcTRjb1Vq
      S2V5WkhGRUNIRDRGOEN6K2Nub0NJRis5S3BXdwoxSTFTZTVkOFJUM2NHYkRHSnZKV1g0VVkzdXpm
      ZEppQUZuZ3gKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI0CgZBZG1pbnMSKhIg
      CAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNlbWVudBIo
      Eh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdSZWFkZXJzEigSHggB
      EhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhII
      EgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRp
      b25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVy
      L0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggK
      BlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZB
      ZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWluLW5ldDo3
      MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRf
      MxIAGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVy
      cxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZB
      ZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
