apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.193.143.232:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIHPVFEJwJ7f8H00C6i56F3v2DhP8+bsJwaJsQYCEoCK6EpJeCo9eCoxeCngKWggBEAEaBgj4
      gcWkBiIKc3lzY2hhbm5lbCpAM2VjNTY4MGE4MTYzN2IzNjg4NGQ2ZTI2N2E0MTY2ODIzOGFiYjlh
      OTQ2ZWEzMTdlYTcxYjkyMWI3NGNlYmFlNBIaEhj8/mOhHzecZpvrkjAIEDTow7ix6oNj8BgSj10K
      jF0SiV0SkSsKB09yZGVyZXIShSsSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVZWN3QStjS0ZSQ05iVnpSekV3VDI2d2ZXODZRd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TmpJd01EVTBOalV4V2hjTk1qWXdOREE1TURVME5qVXhX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJENFJM
      dUg1RDRNZnhOWURWU0tYaTRKdWRpNDB3RWJWalBBVGZoZ0F3ZUpERG1rcEpra2MKMVp2NnFKRnlv
      UnpMZG51c0lQUjIxTkl3dzVjR2RhbWN6dFNqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0hMVUJwcXo3RDcxd2REQ1E3ZmNTWTF5
      ckliVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQTVJT1dPalh0OGc1NVhYM0NLMWlkQkpFY1hL
      V3VURUVmZkZoeGtaMDMKUDJBQ0lCU3BsZ2cwMENlaTdOWTRjM1pDRmp1V3FmZ2taZFlRS3Q1Wk5q
      ZkF4NTZhCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9lZ0F3SUJBZ0lVVXZXRTN4UzdzYTZRKzlnZC9rTVNKUjNEVkJjd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TmpJd01EVTFOREF3V2hjTk1q
      UXdOakU1TURVMU9UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFRXU0Q0JlSXZBekVMa3FHeTJTTzlBYjhOQ3VZ
      VmVEYUIKTkx4d0ZEOXo2MHhia3h0T3E5ekY5YnpJNHRNbXE5ZFEvMEE3WUNPdUhvazBVZndFNUtR
      cHBhT0NBUk13Z2dFUApNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJRdiswVXdWZlRaClVyR2svdDRCRWN5NGxZbEQ1akFmQmdOVkhTTUVHREFXZ0JT
      SExVQnBxejdENzF3ZERDUTdmY1NZMXlySWJUQWoKQmdOVkhSRUVIREFhZ2hoallTMTBiMjlzY3kw
      NE9XWTVOV1E1T0RjdGJYQmtaSEV3Z1lrR0NDb0RCQVVHQndnQgpCSDE3SW1GMGRISnpJanA3SW1G
      aVlXTXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2SW5SeWRXVWlMQ0pvClppNUJabVpwYkds
      aGRHbHZiaUk2SWlJc0ltaG1Ma1Z1Y205c2JHMWxiblJKUkNJNklrRmtiV2x1UUhOMWNIQnMKZVdO
      b1lXbHVMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05J
      QURCRgpBaUVBNlgvWUxhUmNuN213eDJvU2RBRkduYm0vRzErMUlOTGNhQjV0RjZwZ2czUUNJREJH
      R0k1cmI0cEhXaWpICkRyUlA3UHU4aCsrTkl3LzJyYXNqT1JKQU43dlUKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVZWN3QStjS0ZSQ05iVnpSekV3VDI2d2ZXODZRd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TmpJd01EVTBOalV4V2hjTk1qWXdOREE1
      TURVME5qVXhXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJENFJMdUg1RDRNZnhOWURWU0tYaTRKdWRpNDB3RWJWalBBVGZoZ0F3ZUpERG1rcEpra2MK
      MVp2NnFKRnlvUnpMZG51c0lQUjIxTkl3dzVjR2RhbWN6dFNqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0hMVUJwcXo3RDcxd2RE
      Q1E3ZmNTWTF5ckliVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQTVJT1dPalh0OGc1NVhYM0NL
      MWlkQkpFY1hLV3VURUVmZkZoeGtaMDMKUDJBQ0lCU3BsZ2cwMENlaTdOWTRjM1pDRmp1V3FmZ2ta
      ZFlRS3Q1Wk5qZkF4NTZhCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOwoLRW5k
      b3JzZW1lbnQSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyoG
      QWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91
      dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJAoMQ2Fw
      YWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxqKEgoNQ29uc2Vuc3VzVHlwZRL4ERLtEQoI
      ZXRjZHJhZnQS4BEKyREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrTCC0tLS0tQkVHSU4g
      Q0VSVElGSUNBVEUtLS0tLQpNSUlEQXpDQ0FxdWdBd0lCQWdJVUdlR1Y0d1dUWEs5b01UZUR6cnFV
      dkpCTVcyc3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdN
      Qmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5
      TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd05qSXdNRFUx
      TkRBd1doY05NalF3TmpFNU1EVTFPVEF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVF
      QnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcK
      RGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGph
      R0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVRSYVhmeFU4b2xw
      TGhDSDZOaUd4Tm1EWFhWCmJycFg3WUtMMktLbDJ6WEpFQmhGbVBHMUlGR0dpVTBpY2pqVWUrV2Z5
      Y0tZNnV4dWlsaWN5bHlJUklaUm80SUIKTWpDQ0FTNHdEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdB
      MVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFN
      QjBHQTFVZERnUVdCQlNyTHBWSnVTRENUK05mbXBUMGNLV0IxMS9KCjBqQWZCZ05WSFNNRUdEQVdn
      QlNITFVCcHF6N0Q3MXdkRENRN2ZjU1kxeXJJYlRCQkJnTlZIUkVFT2pBNGdoaHYKY21SbGNtVnlN
      UzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NIRzl5WkdWeVpYSXhMblZ3WjNKaFpHVXVkWEJuY21Gawpa
      UzVqYjIwd2JBWUlLZ01FQlFZSENBRUVZSHNpWVhSMGNuTWlPbnNpYUdZdVFXWm1hV3hwWVhScGIy
      NGlPaUlpCkxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSnZjbVJsY21WeU1TNXpkWEJ3YkhsamFH
      RnBiaTF1WlhRaUxDSm8KWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5ZlRBS0JnZ3Foa2pPUFFRREFn
      TkdBREJEQWlBbUF1ZTdXSUNUS2tPNgo5c3FBWWY2cDZOb2x4QlBOSTZuaStpelFNZ2FjUHdJZmMz
      dHpNRENRSlBYUXQwYWdhQ1JpVzF6d0xhU3pxYSs3CiswTjc1Q2ZZUWc9PQotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCiLTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQXpDQ0FxdWdB
      d0lCQWdJVUdlR1Y0d1dUWEs5b01UZUR6cnFVdkpCTVcyc3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFH
      RnBiaTF1WlhRdwpIaGNOTWpNd05qSXdNRFUxTkRBd1doY05NalF3TmpFNU1EVTFPVEF3V2pCeE1R
      c3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1S
      QXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZR
      UURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJn
      Z3Foa2pPUFFNQkJ3TkNBQVRSYVhmeFU4b2xwTGhDSDZOaUd4Tm1EWFhWCmJycFg3WUtMMktLbDJ6
      WEpFQmhGbVBHMUlGR0dpVTBpY2pqVWUrV2Z5Y0tZNnV4dWlsaWN5bHlJUklaUm80SUIKTWpDQ0FT
      NHdEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdF
      RgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNyTHBWSnVTRENUK05mbXBU
      MGNLV0IxMS9KCjBqQWZCZ05WSFNNRUdEQVdnQlNITFVCcHF6N0Q3MXdkRENRN2ZjU1kxeXJJYlRC
      QkJnTlZIUkVFT2pBNGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NIRzl5WkdW
      eVpYSXhMblZ3WjNKaFpHVXVkWEJuY21GawpaUzVqYjIwd2JBWUlLZ01FQlFZSENBRUVZSHNpWVhS
      MGNuTWlPbnNpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpCkxDSm9aaTVGYm5KdmJHeHRaVzUwU1VR
      aU9pSnZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhRaUxDSm8KWmk1VWVYQmxJam9pYjNK
      a1pYSmxjaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTkdBREJEQWlBbUF1ZTdXSUNUS2tPNgo5c3FBWWY2
      cDZOb2x4QlBOSTZuaStpelFNZ2FjUHdJZmMzdHpNRENRSlBYUXQwYWdhQ1JpVzF6d0xhU3pxYSs3
      CiswTjc1Q2ZZUWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiA
      gIAIGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVy
      cxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZB
      ZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5z
      ErEvCgtDb25zb3J0aXVtcxKhLxLWLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtErwuErEXCg9tYW51
      ZmFjdHVyZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEGLS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVRWRMQjhjOG43dVhkM280
      MWJWKzJHZkVTaFZJd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdO
      VkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1
      MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhj
      Tk1qTXdOakl3TURVME9EQTNXaGNOTWpZd05EQTVNRFUwT0RBM1dqQmtNUXN3Q1FZRFZRUUcKRXdK
      RFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05W
      QkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5
      TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCT2s3bFZ2dXNtbmVQSG42
      d2FYajRyMm9SL3FoZWpWNC9JeHAKaGxIZjc4NjFhMzRROStSdGRkSElvdzlmK2wwT2lwNTNsVlZp
      YmJic2RJVzVtdE02T1RlalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgv
      QkFRREFnR21NQjBHQTFVZERnUVdCQlNNTFFWVVZkazEra2RVCndCWndRR2x4LzdrM1hEQUtCZ2dx
      aGtqT1BRUURBZ05JQURCRkFpRUE4MDJzOXd3WmI2STVybzdEMk5DMENYUWUKRTVSWmZwY01JZEl4
      SjZ4UFZhMENJQ0Y4ZnE4VHpMVjcyZG8zYzUvNzFURlJnOUhFa0EyWGlPMy92WGhCTk1FVQotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlE
      RVRDQ0FyZWdBd0lCQWdJVUJ0ejNHcU9yR1ZUcVJoOFFwU0RkdWg1SEN3Z3dDZ1lJS29aSXpqMEVB
      d0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVC
      d3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1F
      Mk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nak13TmpJd01EVTFOVEF3V2hjTk1qUXdO
      akU1TURZd01EQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRRM0xqTTRM
      emd1TlRRdlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpBTUJnTlZC
      QXNUQldGa2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFRRERCWkJa
      RzFwYmtCdFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJCnpqMERB
      UWNEUWdBRWtrNnBPS1R4MmF5TE1CaDNzSnQ3Q0N0dHhHMGpZek5BdE1yTHBLZDJWZlZNMHlMbHBp
      SFUKbEhVRjczM0EvTjdPcmdkdUFIK3VyKzA4eGVDN1EwcG9zcU9DQVNJd2dnRWVNQTRHQTFVZER3
      RUIvd1FFQXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUXgrWms1MTJ0QkJR
      UHp3T3g4cVlHeTNQU2pKakFmCkJnTlZIU01FR0RBV2dCU01MUVZVVmRrMStrZFV3Qlp3UUdseC83
      azNYREFrQmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDROV0pqTkdNMk5UYzBMWEY0T0d4dE1J
      R1hCZ2dxQXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9pZEhKMVpT
      SXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1ZFdaaFkz
      UjFjbVZ5SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgKWTNSMWNt
      VnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05JQURC
      RgpBaUVBcW1xZ3QrQmlaVmZDNTI3aVFST1BudTRHdXRXL0RtR2Nmb2lSMEJBeXo3TUNJRW5sSkJh
      QmtQaXBFWmhsCmpsSUlZaHk4Y1Mwdm9sTXNBR0k5U3NiNVgxUW0KLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SUNERENDQWJLZ0F3SUJBZ0lVRWRMQjhjOG43dVhkM280MWJWKzJHZkVTaFZJd0NnWUlLb1pJemow
      RUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFV
      RUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFN
      TUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qTXdOakl3TURVME9EQTNXaGNOTWpZ
      d05EQTVNRFUwT0RBM1dqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdO
      b01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pF
      Y01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdF
      R0NDcUdTTTQ5QXdFSEEwSUFCT2s3bFZ2dXNtbmVQSG42d2FYajRyMm9SL3FoZWpWNC9JeHAKaGxI
      Zjc4NjFhMzRROStSdGRkSElvdzlmK2wwT2lwNTNsVlZpYmJic2RJVzVtdE02T1RlalFqQkFNQThH
      QTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlNN
      TFFWVVZkazEra2RVCndCWndRR2x4LzdrM1hEQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUE4MDJz
      OXd3WmI2STVybzdEMk5DMENYUWUKRTVSWmZwY01JZEl4SjZ4UFZhMENJQ0Y4ZnE4VHpMVjcyZG8z
      YzUvNzFURlJnOUhFa0EyWGlPMy92WGhCTk1FVQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoG
      QWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1Aa
      BkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQ
      GgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1cmVyTVNQ
      EAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0
      dXJlck1TUBoGQWRtaW5zKgZBZG1pbnMSqhYKCmNhcnJpZXJNU1ASmxYatxQKA01TUBKvFBKkFBKh
      FAoKY2Fycmllck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdB
      d0lCQWdJVUIvZFZOWEVuMjhrY1BpeFl3ZEJsSjZTMzJ6d3dDZ1lJS29aSXpqMEVBd0l3CldqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxX
      NWxkREFlRncweQpNekEyTWpBd05UUTVNamRhRncweU5qQTBNRGt3TlRRNU1qZGFNRm94Q3pBSkJn
      TlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJq
      RVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpY
      UXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVFNUlIxM09TVUlCMUIwS2Z3Y1Zl
      T242UEdsTEdHdWhJckl3elllM21oc0pzSWhlUHZTb2JqaXJtb1dUSm5KCkNGMVcydVpPT2JMVUhW
      TWR0S3JtamJjaG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3
      SUJwakFkQmdOVkhRNEVGZ1FVbjNrNkZSUTJiMytKNEQxVlZ5Q0dkU2o5bFgwd0NnWUlLb1pJemow
      RQpBd0lEUndBd1JBSWdNWXRpbEZaMlpGZjQ1Z1hrZGFuYzJjRUl1YzFnV0xVR2dXb1JNeldOMXR3
      Q0lFRFRmZ0lkCmpGQ2hRcy96elgvVVBiN2t1d3ZVRVZsOS9IWTlEVzdxZmkxZgotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDN1RDQ0Fw
      U2dBd0lCQWdJVVFySk5JR0N2dVorVnE0ZFZPZVliT3hZUGVLMHdDZ1lJS29aSXpqMEVBd0l3Cldq
      RUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5
      dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdW
      eUxXNWxkREFlRncweQpNekEyTWpBd05UVTNNREJhRncweU5EQTJNVGt3TmpBeU1EQmFNSGd4Q3pB
      SkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURB
      T0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVDeE1IWTJG
      eWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRCZ2NxaGtq
      T1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRS3YzZi9zanRXOGhKVHFLeWpHVlpEClNEeStIb09FcWZx
      YUpsYlFZem9oQXZrYWJ3QzM4TUh3OHlzZ2dtSmdxMFNZVGgxckxIL0VsQTZEc2RtTlVCNEkKbzRJ
      QkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBP
      QkJZRQpGTk50QkxKUEJrbWtyYmFtSXJKM2tmeXF2REFrTUI4R0ExVWRJd1FZTUJhQUZKOTVPaFVV
      Tm05L2llQTlWVmNnCmhuVW8vWlY5TUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4ekxUYzJZalE0
      Tm1abU5EUXRPR0pyWjNnd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJNmV5SmhZbUZq
      TG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVdabWFXeHBZWFJw
      YjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdSdGFXNUFZMkZ5
      Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29aSXpqMEVBd0lE
      UndBd1JBSWdXaG52OGJVNExLTGVMbWF0TndWaXgwR2lRUkpOaWh6K0pSb1YvYVQ0Sk1jQwpJRTI3
      Zy91azZEa0hsVEJBYXRhdG45VzY3VGJTb2NEYlJobGtSaEpVUUlvcQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK5QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQjl6Q0NBWjZnQXdJQkFnSVVCL2RWTlhFbjI4a2NQaXhZd2RCbEo2UzMyend3Q2dZSUtvWkl6
      ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdB
      MVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZ
      UzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTXpBMk1qQXdOVFE1TWpkYUZ3MHlOakEwTURrd05UUTVN
      amRhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZC
      QWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZ
      MkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFRTVJSMTNP
      U1VJQjFCMEtmd2NWZU9uNlBHbExHR3VoSXJJd3pZZTNtaHNKc0loZVB2U29iamlybW9XVEpuSgpD
      RjFXMnVaT09iTFVIVk1kdEtybWpiY2hvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0Ex
      VWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVW4zazZGUlEyYjMrSjREMVZWeUNHZFNqOWxY
      MHdDZ1lJS29aSXpqMEUKQXdJRFJ3QXdSQUlnTVl0aWxGWjJaRmY0NWdYa2RhbmMyY0VJdWMxZ1dM
      VUdnV29STXpXTjF0d0NJRURUZmdJZApqRkNoUXMvenpYL1VQYjdrdXd2VUVWbDkvSFk5RFc3cWZp
      MWYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoS
      CBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIcEggSBggB
      EgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggBEhoSCBIG
      CAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARIC
      CAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRpb25Qb2xp
      Y3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlu
      cyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAa
      BkFkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tE
      YXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2Vz
      EjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRt
      aW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMS
      CQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zKgZB
      ZG1pbnMaDgoECgIKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
