apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://98.70.9.151:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIBSg0B9WjAGAwxU7MWH9SwLuOCWhHyEY03Mp9X0uBf0REp5eCpteCpheCngKWggBEAEaBgjS
      xc2iBiIKc3lzY2hhbm5lbCpAMGJlNmQ2M2Y1MTY0MWY1NjlhZTA5YzkwZjUxOTJmYmRjYWI0Yjg4
      YWYxOTJjYWFkYWY3ZmMxYjU5ZjcwMjRmZRIaEhg5KEnbJcZJFVjSFmBSC8AOdfXaj0nYEyASm10K
      mF0SlV0SkysKB09yZGVyZXIShysSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVVzNWS0g3OG0xVXBxeEhlSTl1eVFQcXlaQWRrd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRBME1EY3pNVEEwV2hjTk1qWXdNakl4TURjek1UQTBX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJDWm04
      WHNuNE5ac0Yvdmx3Yko5TlNHalREMlp3MVlCbkF2SEZFUTFzUjhuMFBQQ2lOaGUKbmlJMTh2a1RX
      UFowdTBhRXhwSUs2Zmh4RG54NkdxZGtHelNqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVHNvMVZRYTBTZG80UGNseTA3Tmg1Smk5
      cklwekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQXJ6b2hIZGV5ZGNCWSt3M2JLVWowYk9TTnFD
      elEzTmNuMVVUSnd5RFcKTTRRQ0lBYThXZktQNkVRblhveS9tR1U3ZjV5VXd5Z0REVGNsRzc1aTU5
      WmZlQTBlCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVZjhLbFNkd2lSSzVBdjdkUU14YzFSNklWMnpjd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRBME1EY3pOekF3V2hjTk1q
      UXdOVEF6TURjME1qQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFZm0zWm14cFhGTG1tajh1Y0RCdEZDdkk1TzEw
      ZlBRbnIKWFJoZ3paMjZyT3lsZms5Q2xlL3M2NndkUXlLcVBwVi9aTGhWVUhPakRoU0dSTCtwcWxY
      VGFhT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJRYWg1T0xSaTYrCkcrMlM4eXBvaGtldXRDU3JvVEFmQmdOVkhTTUVHREFXZ0JU
      c28xVlFhMFNkbzRQY2x5MDdOaDVKaTlySXB6QWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      M05HUTBaalUyWkdNMUxXNDJZM0J0TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnVDhVN1dINVMrZW1aK0ZaNGVmTTdlMDZzWjRzd091RERZcHlUK1FQMnc1NENJRVNW
      U2tUbjA5WGx3SHJhCnJ2UHJobGVIL2l6VXByTzFya2dXYXg1QjgyNXYKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVVzNWS0g3OG0xVXBxeEhlSTl1eVFQcXlaQWRrd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRBME1EY3pNVEEwV2hjTk1qWXdNakl4
      TURjek1UQTBXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJDWm04WHNuNE5ac0Yvdmx3Yko5TlNHalREMlp3MVlCbkF2SEZFUTFzUjhuMFBQQ2lOaGUK
      bmlJMTh2a1RXUFowdTBhRXhwSUs2Zmh4RG54NkdxZGtHelNqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVHNvMVZRYTBTZG80UGNs
      eTA3Tmg1Smk5cklwekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQXJ6b2hIZGV5ZGNCWSt3M2JL
      VWowYk9TTnFDelEzTmNuMVVUSnd5RFcKTTRRQ0lBYThXZktQNkVRblhveS9tR1U3ZjV5VXd5Z0RE
      VGNsRzc1aTU5WmZlQTBlCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHUmVh
      ZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiYKDENhcGFiaWxpdGllcxIW
      EgwKCgoGVjFfNF8yEgAaBkFkbWlucxqKEgoNQ29uc2Vuc3VzVHlwZRL4ERLtEQoIZXRjZHJhZnQS
      4BEKyREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrTCC0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlEQlRDQ0FxdWdBd0lCQWdJVU4rcVlzZUVpcWhnZkZaeWdDOHlzUnl3UlA2TXdD
      Z1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURW
      UVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd05UQTBNRGN6TnpBd1doY05N
      alF3TlRBek1EYzBNakF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVO
      VEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxF
      d2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpa
      WFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFsRzNQUE5vUTIvYm9TWW5rUlVq
      bDZDa3FKCmpJNDJwOFd2Uk5aNTZTZTBZZ0dSK0hscVBzV2YzcDlnU245dzVnVFNEQU95MjdVdTV4
      TGQ1K0tPb1J3TW80SUIKTWpDQ0FTNHdEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01C
      UUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERn
      UVdCQlNBWTlwcFBEdlNmSVU0eHdMQXNPZEQxQXFCCmdUQWZCZ05WSFNNRUdEQVdnQlRzbzFWUWEw
      U2RvNFBjbHkwN05oNUppOXJJcHpCQkJnTlZIUkVFT2pBNGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JI
      bGphR0ZwYmkxdVpYU0NIRzl5WkdWeVpYSXhMblZ3WjNKaFpHVXVkWEJuY21GawpaUzVqYjIwd2JB
      WUlLZ01FQlFZSENBRUVZSHNpWVhSMGNuTWlPbnNpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpCkxD
      Sm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSnZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhR
      aUxDSm8KWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlF
      QXBKZk1nbWF2UXZGTwpBdGlkVEtobk0xNWovZmJlMDFwUFZOeVo5T0xCZW9VQ0lGeWhVZDZ1MHBS
      NXM5eWY0RVMzbW9hLytYYUM0VkdlCmR3THI2ZndEN3JENAotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCiLTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQlRDQ0FxdWdBd0lCQWdJVU4r
      cVlzZUVpcWhnZkZaeWdDOHlzUnl3UlA2TXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJo
      TUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0Rn
      WURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhR
      dwpIaGNOTWpNd05UQTBNRGN6TnpBd1doY05NalF3TlRBek1EYzBNakF3V2pCeE1Rc3dDUVlEVlFR
      R0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFR
      S0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21S
      bGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFN
      QkJ3TkNBQVFsRzNQUE5vUTIvYm9TWW5rUlVqbDZDa3FKCmpJNDJwOFd2Uk5aNTZTZTBZZ0dSK0hs
      cVBzV2YzcDlnU245dzVnVFNEQU95MjdVdTV4TGQ1K0tPb1J3TW80SUIKTWpDQ0FTNHdEZ1lEVlIw
      UEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpB
      TUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNBWTlwcFBEdlNmSVU0eHdMQXNPZEQxQXFC
      CmdUQWZCZ05WSFNNRUdEQVdnQlRzbzFWUWEwU2RvNFBjbHkwN05oNUppOXJJcHpCQkJnTlZIUkVF
      T2pBNGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NIRzl5WkdWeVpYSXhMblZ3
      WjNKaFpHVXVkWEJuY21GawpaUzVqYjIwd2JBWUlLZ01FQlFZSENBRUVZSHNpWVhSMGNuTWlPbnNp
      YUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpCkxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSnZjbVJs
      Y21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhRaUxDSm8KWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5
      ZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQXBKZk1nbWF2UXZGTwpBdGlkVEtobk0xNWovZmJl
      MDFwUFZOeVo5T0xCZW9VQ0lGeWhVZDZ1MHBSNXM5eWY0RVMzbW9hLytYYUM0VkdlCmR3THI2ZndE
      N3JENAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAKGgZBZG1p
      bnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4S
      BAoCMnMaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5z
      IiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoH
      V3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zKgZBZG1p
      bnMSuS8KC0NvbnNvcnRpdW1zEqkvEt4uChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SxC4SsRcKD21h
      bnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVERVB1MEhnK1EyL0ZM
      ZUp3YTR6amdONVZ2YWd3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5C
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5Z
      VzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdI
      aGNOTWpNd05UQTBNRGN6TWpJeFdoY05Nall3TWpJeE1EY3pNakl4V2pCa01Rc3dDUVlEVlFRRwpF
      d0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJn
      TlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNt
      VnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJLOFcweENhblhNZ2Ry
      V0k0RkljbE9ZcFpXSEZsWDV4OXVGYwo0RUdFbVI5NDFxM3NEdFJ1RTJZVXBQK250KzkrUXFwV3hh
      YWdvYWcySVplWGIrS3BRRHFqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFR
      SC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUVhGcWkvd2JpM29EckgKRnZNdFhSWjFYcTN6L0RBS0Jn
      Z3Foa2pPUFFRREFnTklBREJGQWlFQTF0M0ZzMXBQZlRmM1pJdjJrR0hIZjYxZQpBNVh2YS8xMFd5
      dzJwUDVqMUN3Q0lHTUpkRGdQZ1ZBTE8zOXZidjFTVEpJNk1CdzQ4VXJoajZ4aXpnd3hCYXozCi0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SUREekNDQXJhZ0F3SUJBZ0lUTm41cTVaQkxoNGd6MHdMYnZwVjExTmhMT0RBS0JnZ3Foa2pPUFFR
      REFqQmsKTVFzd0NRWURWUVFHRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFR
      SERBWmFkWEpwWTJneApGVEFUQmdOVkJBb01ERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3
      VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5CkxXNWxkREFlRncweU16QTFNRFF3TnpNNE1EQmFGdzB5TkRB
      MU1ETXdOelF6TURCYU1JR0dNUXN3Q1FZRFZRUUcKRXdKRFNERWFNQmdHQTFVRUJ4TVJORGN1TXpn
      dk9DNDFOQzlhZFhKcFkyZ3hGVEFUQmdOVkJBb1RERTFoYm5WbQpZV04wZFhKbGNqRWpNQXdHQTFV
      RUN4TUZZV1J0YVc0d0V3WURWUVFMRXd4dFlXNTFabUZqZEhWeVpYSXhIekFkCkJnTlZCQU1NRmtG
      a2JXbHVRRzFoYm5WbVlXTjBkWEpsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak8KUFFN
      QkJ3TkNBQVJHZWFUZzRhWnBiVDRRSjNmNTM2SlVzNllxaVo1eDBocmVzRE0vV21tSmJHdmRPSWgw
      Y2l2VQpOS2dxLzNsOTZOMWZSMVRMSVhDakcwMnRXTmdRUThRWm80SUJJakNDQVI0d0RnWURWUjBQ
      QVFIL0JBUURBZ2VBCk1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllFRlBQVGcydHRYRmtW
      ODZDQ0tHUEN0ZnZaSzZXV01COEcKQTFVZEl3UVlNQmFBRkJjV3FML0J1TGVnT3NjVzh5MWRGblZl
      cmZQOE1DUUdBMVVkRVFRZE1CdUNHV05oTFhSdgpiMnh6TFRnMFlqVTVPRFUxWWpRdFltZzNNamN3
      Z1pjR0NDb0RCQVVHQndnQkJJR0tleUpoZEhSeWN5STZleUpoClltRmpMbWx1YVhRaU9pSjBjblZs
      SWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIyNGkKT2lKdFlXNTFabUZq
      ZEhWeVpYSWlMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQnRZVzUxWm1GagpkSFZ5
      WlhJdGJtVjBJaXdpYUdZdVZIbHdaU0k2SW1Ga2JXbHVJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwY0FN
      RVFDCklBeG9oSEl1cmhld3plTHMzTGk5RXp2L3QwSGFnYlN1SENwSWJteWxnR1lDQWlBUlZvd0R4
      U0FsVjhXWjR1MmYKa2QvWHpkdTZiN001d0czRXlVK29rMFEyQnc9PQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQ0REQ0NBYktnQXdJQkFnSVVERVB1MEhnK1EyL0ZMZUp3YTR6amdONVZ2YWd3Q2dZSUtvWkl6
      ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdB
      MVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZC
      QU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpNd05UQTBNRGN6TWpJeFdoY05N
      all3TWpJeE1EY3pNakl4V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlh
      V05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxj
      akVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlB
      Z0VHQ0NxR1NNNDlBd0VIQTBJQUJLOFcweENhblhNZ2RyV0k0RkljbE9ZcFpXSEZsWDV4OXVGYwo0
      RUdFbVI5NDFxM3NEdFJ1RTJZVXBQK250KzkrUXFwV3hhYWdvYWcySVplWGIrS3BRRHFqUWpCQU1B
      OEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JC
      UVhGcWkvd2JpM29EckgKRnZNdFhSWjFYcTN6L0RBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTF0
      M0ZzMXBQZlRmM1pJdjJrR0hIZjYxZQpBNVh2YS8xMFd5dzJwUDVqMUN3Q0lHTUpkRGdQZ1ZBTE8z
      OXZidjFTVEpJNk1CdzQ4VXJoajZ4aXpnd3hCYXozCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      GgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1T
      UBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJN
      U1AaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVyZXJN
      U1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZh
      Y3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxKyFgoKY2Fycmllck1TUBKjFhq/FAoDTVNQErcUEqwU
      EqkUCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2
      Z0F3SUJBZ0lVYVBTK3VZenB5TkZuZDV2RjJDK2FiMWQ0YVh3d0NnWUlLb1pJemowRUF3SXcKV2pF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5
      TFc1bGREQWVGdzB5Ck16QTFNRFF3TnpNek16bGFGdzB5TmpBeU1qRXdOek16TXpsYU1Gb3hDekFK
      QmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2
      YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1
      WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUndrbWo0Wm9xcFFWV25MU0tH
      bGZPR1ZEaEdOZUxGd1B1N3J5K1NYQUxVT0dOcDJDbGZMRmJ3Y2Npa0xyWS8KcGY1dDdiMzFoV25x
      bzZJbjBYWk1KcFArbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FF
      QXdJQnBqQWRCZ05WSFE0RUZnUVVuSEZIcUZjc2ZSN0dWZCt0amNWVkk4WkNrak13Q2dZSUtvWkl6
      ajBFCkF3SURTQUF3UlFJaEFQdmlsdGhwaSs3UkRnWmhuZkhoM1ZlSDF5c0dVZWM4STJrWThXQWEv
      Mjd2QWlCTUhVdHcKVWJXakd4SjkxRkQ2bFhmUU55WEZCZUhjdXBiRGdjNzBIc1hCeWc9PQotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlD
      N1RDQ0FwU2dBd0lCQWdJVUVIOTlzUUREd3c1c2tzL2pmR2hyZHYyQjBNTXdDZ1lJS29aSXpqMEVB
      d0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVC
      d3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZ
      WEp5YVdWeUxXNWxkREFlRncweQpNekExTURRd056UXhNREJhRncweU5EQTFNRE13TnpRMk1EQmFN
      SGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWti
      MjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVD
      eE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRC
      Z2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSNitldTBVL0dkQ0JPV1VxOUJlTGt6CkhQdDcy
      QlIyMjRBQWt0Ni94TVhablpHb1BkVW0rN1o1SjJCMi9tUytad3dhN1FjbWhTVnE4Z3ZrakViQTdr
      YmMKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hR
      WURWUjBPQkJZRQpGSFJ6ZXB4WWxQY1JJeVpEUkt6bStCdXJGOWpxTUI4R0ExVWRJd1FZTUJhQUZK
      eHhSNmhYTEgwZXhsWGZyWTNGClZTUEdRcEl6TUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4ekxU
      WmlObVprTkRRME5tUXRjV0kyYTNFd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJNmV5
      SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVdabWFX
      eHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdSdGFX
      NUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29aSXpq
      MEVBd0lEUndBd1JBSWdZMWR1emhiWklyYzhxQXJ4dHJLNEdBQnZKRm9XZ2diRExJVDdjZGZvUzk0
      QwpJRWdYclowSkpqS1dObHVadU81SmI5d2E3bFZ0ZHpSZS9JZFNoVS9HTXBKOQotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVhUFMrdVl6cHlORm5kNXZGMkMrYWIxZDRhWHd3Q2dZ
      SUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFR
      RERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTXpBMU1EUXdOek16TXpsYUZ3MHlOakF5TWpF
      d056TXpNemxhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpB
      TkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3
      T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFS
      d2ttajRab3FwUVZXbkxTS0dsZk9HVkRoR05lTEZ3UHU3cnkrU1hBTFVPR05wMkNsZkxGYndjY2lr
      THJZLwpwZjV0N2IzMWhXbnFvNkluMFhaTUpwUCtvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgv
      TUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVW5IRkhxRmNzZlI3R1ZkK3RqY1ZW
      SThaQ2tqTXdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQVB2aWx0aHBpKzdSRGdaaG5mSGgzVmVI
      MXlzR1VlYzhJMmtZOFdBYS8yN3ZBaUJNSFV0dwpVYldqR3hKOTFGRDZsWGZRTnlYRkJlSGN1cGJE
      Z2M3MEhzWEJ5Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNAoGQWRtaW5z
      EioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5kb3JzZW1l
      bnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHUmVhZGVycxIo
      Eh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigSHggB
      EhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENy
      ZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwK
      CgoGVjFfNF8zEgAaBkFkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2GgZBZG1p
      bnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxpOChBPcmRl
      cmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0OjcwNTAaFy9DaGFubmVs
      L09yZGVyZXIvQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dy
      aXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQ
      AhoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
