apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.244.7.50:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIP5RR9Nbvob3UrdyRIJZqOWCFzvLtSS39Naiuozq1FPGEp5eCpteCpheCngKWggBEAEaBgi9
      nL+hBiIKc3lzY2hhbm5lbCpAYTRmZDJmNGM0YTQ0OGY3Yjg1ODYxY2YwMjk5NTg2N2Y3Y2MxYzYz
      NTZiOTgzZmZmM2NhZDQyYmNjNTVlNGFkZBIaEhhi79v+jvJSPiwIu0jO/iiZyHIMWIKgkTQSm10K
      mF0SlV0SkysKB09yZGVyZXIShysSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVYW9nSWdVWGFiR1VacUptaEh3OWR6SVFndGpZd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TkRBM01EYzBPRE00V2hjTk1qWXdNVEkxTURjME9ETTRX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJNWFBz
      aSsySWNITTlmUXd1OTRDOVNTQkhPR2JYTU1WVWtTcFhDRFZhZFFyeWpsRVRoZ28KazRBWTBjeTJ1
      eTR5bTEyelJMRW5GNmV1TDNYazBPWWtnVHFqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUUp3Qk5pc0VIb1JKdDEzY1dEaCt4em84
      M09XakFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBcHJKNWx3NE9WSkJObEE1NVlqWUtHd2tJTmN0
      RzE2T055Wm1WalRSL1YKeUFJaEFLT0NMSHpINmJjVmlIOXkxWDdhMWdpMTZwSGNSVFN6S0xxMkZG
      eVBWVk44Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVRnUvNFpZeEhyakwyK2liUGtIdXc1YjNPOVA4d0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TkRBM01EYzFOREF3V2hjTk1q
      UXdOREEyTURjMU9UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFVTIzZ3V5M2ZjZEthUmVLZ0tDZlZ0NElkck9v
      Y3RtRmwKTVJyVDg2bWptN2VKMXluTDdsMy92K3JGOUc0ZERYb0xNdi93Z3pkNFdpd1N6cFk0VjRl
      RkdLT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJUUkhxNzBtR2FECmpuNVA3ejNoaTN0djR2WWdEekFmQmdOVkhTTUVHREFXZ0JR
      SndCTmlzRUhvUkp0MTNjV0RoK3h6bzgzT1dqQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qbG1ZMlptWkdSakxUZzJkMk5zTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnWk1wUUdlNVdNbmNrOXNsU1BQNjdPYktuSU1ncm1LOTRkeldEdHltRjB1OENJRkRr
      OER2d2Q1OVpsRk9aClVpQ1ZYbTllQmN3WHJsb1ZEZVM0SzFHcTFXQzYKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVYW9nSWdVWGFiR1VacUptaEh3OWR6SVFndGpZd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TkRBM01EYzBPRE00V2hjTk1qWXdNVEkx
      TURjME9ETTRXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJNWFBzaSsySWNITTlmUXd1OTRDOVNTQkhPR2JYTU1WVWtTcFhDRFZhZFFyeWpsRVRoZ28K
      azRBWTBjeTJ1eTR5bTEyelJMRW5GNmV1TDNYazBPWWtnVHFqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUUp3Qk5pc0VIb1JKdDEz
      Y1dEaCt4em84M09XakFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBcHJKNWx3NE9WSkJObEE1NVlq
      WUtHd2tJTmN0RzE2T055Wm1WalRSL1YKeUFJaEFLT0NMSHpINmJjVmlIOXkxWDdhMWdpMTZwSGNS
      VFN6S0xxMkZGeVBWVk44Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHUmVh
      ZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiYKDENhcGFiaWxpdGllcxIW
      EgwKCgoGVjFfNF8yEgAaBkFkbWlucxqKEgoNQ29uc2Vuc3VzVHlwZRL4ERLtEQoIZXRjZHJhZnQS
      4BEKyREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrTCC0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlEQlRDQ0FxdWdBd0lCQWdJVVFoS0xrcHRIOGlJNXV6bjhUeWRhdHpVWDBIb3dD
      Z1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURW
      UVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd05EQTNNRGMxTkRBd1doY05N
      alF3TkRBMk1EYzFPVEF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVO
      VEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxF
      d2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpa
      WFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVR4V3VhTVFzb3AwWnRaa0J6c1ph
      ZCtmSVpkCkZvRmFMbys0NWkyWXlYc3pEU3FIZVhRTHE5a3NaejlINUsrdEZkQlRyb1J5elFrZVVJ
      QXpaMUVFQy9ZSm80SUIKTWpDQ0FTNHdEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01C
      UUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERn
      UVdCQlJ1OFN2U1kwN2NwTEVlL2hEeW95UGtaK24zCmpUQWZCZ05WSFNNRUdEQVdnQlFKd0JOaXNF
      SG9SSnQxM2NXRGgreHpvODNPV2pCQkJnTlZIUkVFT2pBNGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JI
      bGphR0ZwYmkxdVpYU0NIRzl5WkdWeVpYSXhMblZ3WjNKaFpHVXVkWEJuY21GawpaUzVqYjIwd2JB
      WUlLZ01FQlFZSENBRUVZSHNpWVhSMGNuTWlPbnNpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpCkxD
      Sm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSnZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhR
      aUxDSm8KWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlF
      QTVnQ1ZCVTdYaGU5SApJaXd3dEtKOGVKWmhuTlFTcndmWDZSTksxdlh5YjVjQ0lDeGpiR21WQ1Fu
      WXliRTRCbHA1cU9QQldOQzZwV2x5ClE5UVNLc1cxRThpZAotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCiLTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQlRDQ0FxdWdBd0lCQWdJVVFo
      S0xrcHRIOGlJNXV6bjhUeWRhdHpVWDBIb3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJo
      TUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0Rn
      WURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhR
      dwpIaGNOTWpNd05EQTNNRGMxTkRBd1doY05NalF3TkRBMk1EYzFPVEF3V2pCeE1Rc3dDUVlEVlFR
      R0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFR
      S0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21S
      bGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFN
      QkJ3TkNBQVR4V3VhTVFzb3AwWnRaa0J6c1phZCtmSVpkCkZvRmFMbys0NWkyWXlYc3pEU3FIZVhR
      THE5a3NaejlINUsrdEZkQlRyb1J5elFrZVVJQXpaMUVFQy9ZSm80SUIKTWpDQ0FTNHdEZ1lEVlIw
      UEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpB
      TUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJ1OFN2U1kwN2NwTEVlL2hEeW95UGtaK24z
      CmpUQWZCZ05WSFNNRUdEQVdnQlFKd0JOaXNFSG9SSnQxM2NXRGgreHpvODNPV2pCQkJnTlZIUkVF
      T2pBNGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NIRzl5WkdWeVpYSXhMblZ3
      WjNKaFpHVXVkWEJuY21GawpaUzVqYjIwd2JBWUlLZ01FQlFZSENBRUVZSHNpWVhSMGNuTWlPbnNp
      YUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpCkxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSnZjbVJs
      Y21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhRaUxDSm8KWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5
      ZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTVnQ1ZCVTdYaGU5SApJaXd3dEtKOGVKWmhuTlFT
      cndmWDZSTksxdlh5YjVjQ0lDeGpiR21WQ1FuWXliRTRCbHA1cU9QQldOQzZwV2x5ClE5UVNLc1cx
      RThpZAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAKGgZBZG1p
      bnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4S
      BAoCMnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1p
      bnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoH
      V3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zKgZBZG1p
      bnMSuS8KC0NvbnNvcnRpdW1zEqkvEt4uChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SxC4SsRcKD21h
      bnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVJOVNUU1RsSDhYZTRU
      bE5NUFo5S0VEWE5tTkV3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5C
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5Z
      VzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdI
      aGNOTWpNd05EQTNNRGMwT1RVMVdoY05Nall3TVRJMU1EYzBPVFUxV2pCa01Rc3dDUVlEVlFRRwpF
      d0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJn
      TlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNt
      VnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJCaVNWUys1QW9CNnRi
      cnl3ZEFZTTN6Q25sYzNwUlJJTVY5NQpTRm5DaEVSbkVhem5aQVNESEtBMy93WEtST0FqNVV4dnUw
      NXZIMHN0U0pETU5FeDFrd1dqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFR
      SC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUkp3cjR0cjJPV0puT2gKa1llUlBHQ2YwdzdyK2pBS0Jn
      Z3Foa2pPUFFRREFnTklBREJGQWlFQWtaVFU1Z2NUMG8rWis0Z01vRkJjVEJQZAovcUR1cHN3SzZJ
      RUtuTE1OQmVvQ0lFZzl5S0d6MHBZQlBUeTgzNXAzalBnc0RLRG5iYWd3RFpVVnNSWUtGOWJ4Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SURFVENDQXJlZ0F3SUJBZ0lVSzRDZk5SVlVxYnhDSitBL0FnaGd5K2p5dGVjd0NnWUlLb1pJemow
      RUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFV
      RUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFN
      TUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qTXdOREEzTURjMU5qQXdXaGNOTWpR
      d05EQTJNRGd3TVRBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEzTGpN
      NEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFNQmdO
      VkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFEREJa
      QlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkKemow
      REFRY0RRZ0FFM0FpTHVmWjZtNDNsZWFvUUZHdm44VDVjT2Y5TXBnK3c2c2VqR285M3lPbHc2VmEv
      V01YUApaWUhHUVdGOWlncFNMR0hrUEdCTDVaYXMrdnN1MjU3eTY2T0NBU0l3Z2dFZU1BNEdBMVVk
      RHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUa0YrR3h3QTdK
      bVJLb1I4ek5QYW9QRHAyOEdqQWYKQmdOVkhTTUVHREFXZ0JSSndyNHRyMk9XSm5PaGtZZVJQR0Nm
      MHc3citqQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwM1ptTmtZMlptTm1Ka0xXdzJjM001
      TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lkSEox
      WlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVkV1po
      WTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZM1Ix
      Y21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTklB
      REJGCkFpRUF0Q2hnTkhSSlVMWUplWi8yencxQTAzcTFaV29JTHFBTDFMSlBvaXVvR1ZrQ0lEUFRy
      RnJrblV6TGR1MUgKOHNVcjIxdGZFMDc5aHQzNjU5YXVaNWlVNVhwRAotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQ0REQ0NBYktnQXdJQkFnSVVJOVNUU1RsSDhYZTRUbE5NUFo5S0VEWE5tTkV3Q2dZSUtvWkl6
      ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdB
      MVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZC
      QU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpNd05EQTNNRGMwT1RVMVdoY05N
      all3TVRJMU1EYzBPVFUxV2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlh
      V05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxj
      akVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlB
      Z0VHQ0NxR1NNNDlBd0VIQTBJQUJCaVNWUys1QW9CNnRicnl3ZEFZTTN6Q25sYzNwUlJJTVY5NQpT
      Rm5DaEVSbkVhem5aQVNESEtBMy93WEtST0FqNVV4dnUwNXZIMHN0U0pETU5FeDFrd1dqUWpCQU1B
      OEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JC
      Ukp3cjR0cjJPV0puT2gKa1llUlBHQ2YwdzdyK2pBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQWta
      VFU1Z2NUMG8rWis0Z01vRkJjVEJQZAovcUR1cHN3SzZJRUtuTE1OQmVvQ0lFZzl5S0d6MHBZQlBU
      eTgzNXAzalBnc0RLRG5iYWd3RFpVVnNSWUtGOWJ4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      GgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1cmVyTVNQ
      EAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0
      dXJlck1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFj
      dHVyZXJNU1AaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZh
      Y3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxKyFgoKY2Fycmllck1TUBKjFhq/FAoDTVNQErcUEqwU
      EqkUCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2
      Z0F3SUJBZ0lVUytycmhObkYvT3J1djI5K3RDTXREL1dITHpJd0NnWUlLb1pJemowRUF3SXcKV2pF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5
      TFc1bGREQWVGdzB5Ck16QTBNRGN3TnpVeE1UVmFGdzB5TmpBeE1qVXdOelV4TVRWYU1Gb3hDekFK
      QmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2
      YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1
      WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUjRwRmtDYll3b3FKbFV1ampo
      ZlBTM2s0RXJYaFF2TkE4bytJMnl2dkhEWXZUeFB1UGxWMERMc2NNQzQ4NXMKUUY0QmdsTWhDSXdL
      N24rUy9WY3lJRm9qbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FF
      QXdJQnBqQWRCZ05WSFE0RUZnUVVQTjZnUjh3OUZZVDlSWk1EN1FvTEZUR2JBYjh3Q2dZSUtvWkl6
      ajBFCkF3SURTQUF3UlFJaEFJZ2JpUnBaL3g0WGlVWXg1UkJaNlk3R3IyOTd4a3ZsZkg3N2d6MHFO
      SEpRQWlCNDVRNUUKMG5mVVE2T0haQzNpdnBSUkJnc21sZHl5emxaSXBuNHkzRVJHN1E9PQotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlD
      N1RDQ0FwU2dBd0lCQWdJVUVHQmNhOEk3bVAvc0p5SWZHRE5yZzBjZWkxOHdDZ1lJS29aSXpqMEVB
      d0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVC
      d3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZ
      WEp5YVdWeUxXNWxkREFlRncweQpNekEwTURjd056VTNNREJhRncweU5EQTBNRFl3T0RBeU1EQmFN
      SGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWti
      MjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVD
      eE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRC
      Z2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUeG5xOWpnS0JZcDNaUHRKQ0JBSy9BCmh4ZUNo
      eVlGQm5FTlNZUmRmeFhjZjVucncySDlNcVJYby9PdGVLSGxGaHlVQW42ZEZjdzg5TEZZMytMNit0
      MDkKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hR
      WURWUjBPQkJZRQpGRnc2QllPSFY5a2RQZzIyalZnNHZ3MmdNblJJTUI4R0ExVWRJd1FZTUJhQUZE
      emVvRWZNUFJXRS9VV1RBKzBLCkN4VXhtd0cvTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4ekxU
      ZGlOVFk1T0RZNE5UWXRjMmN5ZEhZd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJNmV5
      SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVdabWFX
      eHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdSdGFX
      NUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29aSXpq
      MEVBd0lEUndBd1JBSWdaSFJQcExTOXR3R3M4VDFVZkJlbllQV2duSGpEeUluaFQ0c3B1L04wNTlv
      QwpJSFE0NDVNQ3BPUFZ4Tzc0K0xOcnZ1R0Y4d1VpaVBJdTYvWHY1a0QrQmx1SwotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVTK3JyaE5uRi9PcnV2MjkrdENNdEQvV0hMekl3Q2dZ
      SUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFR
      RERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTXpBME1EY3dOelV4TVRWYUZ3MHlOakF4TWpV
      d056VXhNVFZhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpB
      TkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3
      T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFS
      NHBGa0NiWXdvcUpsVXVqamhmUFMzazRFclhoUXZOQThvK0kyeXZ2SERZdlR4UHVQbFYwRExzY01D
      NDg1cwpRRjRCZ2xNaENJd0s3bitTL1ZjeUlGb2pvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgv
      TUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVVBONmdSOHc5RllUOVJaTUQ3UW9M
      RlRHYkFiOHdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQUlnYmlScFoveDRYaVVZeDVSQlo2WTdH
      cjI5N3hrdmxmSDc3Z3owcU5ISlFBaUI0NVE1RQowbmZVUTZPSFpDM2l2cFJSQmdzbWxkeXl6bFpJ
      cG40eTNFUkc3UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiMwoHV3JpdGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyI0CgZBZG1pbnMSKhIg
      CAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNlbWVudBIo
      Eh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdSZWFkZXJzEigSHggB
      EhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENy
      ZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0S
      EhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////
      DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5zdXBwbHljaGFpbi1u
      ZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZW
      MV80XzMSABoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1Jl
      YWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVy
      cxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
