apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: peer0-manufacturer-cli
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Karthikey22/bevel.git
    path: platforms/hyperledger-fabric/charts/fabric_cli
    targetRevision: HEAD
    helm:
      releaseName:  peer0-manufacturer-cli
      values: |-
        metadata:
          namespace: manufacturer-net
          images:
            fabrictools: hyperledger/fabric-tools:1.4.8
            alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        storage:
          class: manufacturersc
          size: 256Mi
        vault:
          role: vault-role
          address: http://52.229.229.54:8200
          authpath: localmanufacturer-net-auth
          adminsecretprefix: secretsv2/data/crypto/peerOrganizations/manufacturer-net/users/admin
          orderersecretprefix: secretsv2/data/crypto/peerOrganizations/manufacturer-net/orderer
          serviceaccountname: vault-auth
          imagesecretname: regcred
          tls: false
        peer:
          name: peer0
          localmspid: manufacturerMSP
          tlsstatus: true
          address: peer0.manufacturer-net:7051
        orderer:
          address: orderer1.supplychain-net:7050
  destination:
    server: "https://kubernetes.default.svc"
    namespace: manufacturer-net
  syncPolicy:
    automated:
      # Do not enable pruning yet!
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true
  