apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supplychain-net-ca
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Karthikey22/bevel.git
    path: platforms/hyperledger-fabric/charts/ca
    targetRevision: HEAD
    helm:
      releaseName:  supplychain-net
      values: |-
        metadata:
          namespace: supplychain-net
          images:
            alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
            ca: hyperledger/fabric-ca:1.4.4
        server:
          name: ca
          tlsstatus: true
          admin: supplychain-admin
            
        storage:
          storageclassname: supplychainsc
          storagesize: 512Mi 
        vault:
          role: vault-role
          address: http://52.229.229.54:8200
          authpath: localsupplychain-net-auth
          secretcert: secretsv2/data/crypto/ordererOrganizations/supplychain-net/ca?ca.supplychain-net-cert.pem
          secretkey: secretsv2/data/crypto/ordererOrganizations/supplychain-net/ca?supplychain-net-CA.key
          secretadminpass: secretsv2/data/credentials/supplychain-net/ca/supplychain?user
          serviceaccountname: vault-auth
          imagesecretname: regcred
        service:
          servicetype: ClusterIP
          ports:
            tcp:
              port: 7054
        proxy:
          provider: none
          type: orderer
          external_url_suffix: upgrade.upgrade.com
  destination:
    server: "https://kubernetes.default.svc"
    namespace: supplychain-net
  syncPolicy:
    automated:
      # Do not enable pruning yet!
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true

