
---
- name: Install argocd cli
  shell: |
    curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
    install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
    rm argocd-linux-amd64

- name: Applying it to the cluster
  shell: |
    kubectl create namespace argocd
    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/core-install.yaml
    argocd login --core

- name: Creating the Application and syncing with repo
  shell: |
    kubectl config set-context --current --namespace=argocd 
    argocd app create guestbook --repo https://github.com/Karthikey22/argocd-example-apps.git --path guestbook --dest-server https://kubernetes.default.svc --dest-namespace default
    argocd app sync guestbook