apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: multichain-net-ca
  namespace: multichain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: multichain-net-ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: multichain-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.4
    server:
      name: ca
      tlsstatus: true
      admin: multichain-admin
        
    storage:
      storageclassname: multichainsc
      storagesize: 512Mi 
    vault:
      role: vault-role
      address: http://20.244.7.50:8200
      authpath: localmultichain-net-auth
      secretcert: secretsv2/data/crypto/ordererOrganizations/multichain-net/ca?ca.multichain-net-cert.pem
      secretkey: secretsv2/data/crypto/ordererOrganizations/multichain-net/ca?multichain-net-CA.key
      secretadminpass: secretsv2/data/credentials/multichain-net/ca/multichain?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: none
      type: orderer
      external_url_suffix: upgrade.upgrade.com
