apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: multichain-cacerts-job
  namespace: multichain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: multichain-cacerts-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/generate_cacerts
  values:
    metadata:
      name: multichain
      component_name: multichain-net
      namespace: multichain-net    
      images:
        fabrictools: hyperledger/fabric-tools:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      role: vault-role
      address: http://20.244.7.50:8200
      authpath: localmultichain-net-auth
      secretcryptoprefix: secretsv2/data/crypto/ordererOrganizations/multichain-net/ca
      secretcredentialsprefix: secretsv2/data/credentials/multichain-net/ca/multichain
      serviceaccountname: vault-auth
      imagesecretname: regcred
      
    ca:
      subject: /C=GB/ST=London/L=London/O=Orderer/CN=ca.multichain-net
