apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-cacerts-job
  namespace: supplychain-net
spec:
  interval: 1m
  project: default
  source:
    repoURL: https://github.com/Karthikey22/bevel.git
    path: platforms/hyperledger-fabric/charts/generate_cacerts
    targetRevision: HEAD
    helm:
      releaseName: supplychain-cacerts-job
      values: |-
        metadata:
        name: supplychain
        component_name: supplychain-net
        namespace: supplychain-net    
        images:
            fabrictools: hyperledger/fabric-tools:1.4.8
            alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

        vault:
        role: vault-role
        address: http://52.229.229.54:8200
        authpath: localsupplychain-net-auth
        secretcryptoprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/ca
        secretcredentialsprefix: secretsv2/data/credentials/supplychain-net/ca/supplychain
        serviceaccountname: vault-auth
        imagesecretname: regcred
        
        ca:
        subject: /C=GB/ST=London/L=London/O=Orderer/CN=ca.supplychain-net